apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-dumpcheck
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "1.0.1-SNAPSHOT"
    camel.apache.org/provider: "PIXEL-V2"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "PIXEL-V2 Dump Check Kamelet"
    description: |-
      Message dumping and content checking kamelet for debugging and monitoring.
      Provides capabilities to dump message content to file system and perform basic validation checks.
    required:
      - dumpEnabled
    type: object
    properties:
      dumpEnabled:
        title: Dump Enabled
        description: Enable or disable message dumping functionality
        type: boolean
        default: false
      dumpLocation:
        title: Dump Location
        description: File system location where message dumps will be stored
        type: string
        default: "/opt/out/dumps"
      dumpPrefix:
        title: Dump File Prefix
        description: Prefix for dump file names
        type: string
        default: "msg_dump"
      enableContentCheck:
        title: Enable Content Check
        description: Enable basic content validation and checking
        type: boolean
        default: true
      logLevel:
        title: Log Level
        description: Log level for dump check operations
        type: string
        default: "INFO"
        enum: ["DEBUG", "INFO", "WARN", "ERROR"]
      maxDumpSize:
        title: Maximum Dump Size
        description: Maximum size (in bytes) for message dumps
        type: integer
        default: 1048576
  dependencies:
    - "camel:kamelet"
    - "camel:log"
    - "camel:file"
    - "camel:jackson"
    - "camel:groovy"
  template:
    from:
      uri: "kamelet:source"
      steps:
        # Store original body before any modifications
        - setHeader:
            name: "OriginalMessageBody"
            simple: "${body}"
            
        # Log entry with message info
        - log:
            message: "K-DUMPCHECK: Processing message - Size: ${header.CamelFileLength}, Type: ${header.Content-Type}"
            loggingLevel: "{{logLevel}}"
            
        # Content size validation
        - choice:
            when:
              - simple: "${header.CamelFileLength} > {{maxDumpSize}}"
                steps:
                  - log:
                      message: "K-DUMPCHECK: Message too large for dumping (${header.CamelFileLength} bytes > {{maxDumpSize}} bytes)"
                      loggingLevel: WARN
                  - setHeader:
                      name: "DumpCheckStatus"
                      simple: "SKIPPED_TOO_LARGE"
            otherwise:
              steps:
                # Basic content validation
                - choice:
                    when:
                      - simple: "{{enableContentCheck}} == true"
                        steps:
                          - script:
                              groovy: |
                                // Basic content checks
                                def body = exchange.in.body as String
                                def contentValid = true
                                def validationMessages = []
                                
                                // Check if body is not empty
                                if (!body || body.trim().isEmpty()) {
                                    contentValid = false
                                    validationMessages.add("Empty or null message body")
                                }
                                
                                // Check for basic XML structure if content-type suggests XML
                                def contentType = exchange.in.headers['Content-Type'] as String
                                if (contentType && contentType.contains('xml') && body) {
                                    if (!body.trim().startsWith('<')) {
                                        validationMessages.add("Content-Type suggests XML but body doesn't start with '<'")
                                    }
                                }
                                
                                // Check for basic JSON structure if content-type suggests JSON
                                if (contentType && contentType.contains('json') && body) {
                                    def trimmedBody = body.trim()
                                    if (!trimmedBody.startsWith('{') && !trimmedBody.startsWith('[')) {
                                        validationMessages.add("Content-Type suggests JSON but body doesn't start with '{' or '['")
                                    }
                                }
                                
                                // Set validation results
                                exchange.in.headers['ContentValid'] = contentValid
                                exchange.in.headers['ValidationMessages'] = validationMessages.join('; ')
                                exchange.in.headers['MessageSize'] = body ? body.length() : 0
                          
                          - log:
                              message: "K-DUMPCHECK: Content validation - Valid: ${header.ContentValid}, Messages: ${header.ValidationMessages}"
                              loggingLevel: "{{logLevel}}"
                
                # Conditional message dumping
                - choice:
                    when:
                      - simple: "{{dumpEnabled}} == true"
                        steps:
                          - setHeader:
                              name: "CamelFileName"
                              simple: "{{dumpPrefix}}_${date:now:yyyyMMdd_HHmmss_SSS}_${header.flowOccurId}.txt"
                          
                          - log:
                              message: "K-DUMPCHECK: Dumping message to file: ${header.CamelFileName}"
                              loggingLevel: DEBUG
                          
                          # Create dump file with message and headers info
                          - setBody:
                              simple: |
                                === MESSAGE DUMP ===
                                Timestamp: ${date:now:yyyy-MM-dd HH:mm:ss.SSS}
                                Flow Occur ID: ${header.flowOccurId}
                                Content-Type: ${header.Content-Type}
                                Message Size: ${header.MessageSize} bytes
                                Content Valid: ${header.ContentValid}
                                Validation Messages: ${header.ValidationMessages}
                                
                                === HEADERS ===
                                ${headers}
                                
                                === MESSAGE BODY ===
                                ${header.OriginalMessageBody}
                          
                          - to: "file:{{dumpLocation}}?fileName=${header.CamelFileName}"
                          
                          - setHeader:
                              name: "DumpCheckStatus"
                              simple: "DUMPED"
                              
                          # Restore original body
                          - setBody:
                              simple: "${header.OriginalMessageBody}"
                    otherwise:
                      steps:
                        - setHeader:
                            name: "DumpCheckStatus"
                            simple: "NOT_DUMPED"
                        
                        - log:
                            message: "K-DUMPCHECK: Dump disabled, message not dumped"
                            loggingLevel: DEBUG
        
        # Final status log
        - log:
            message: "K-DUMPCHECK: Processing complete - Status: ${header.DumpCheckStatus}"
            loggingLevel: "{{logLevel}}"
        
        # Send to sink
        - to: "kamelet:sink"