apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-identification-with-redis
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "1.0.1-SNAPSHOT"
    camel.apache.org/provider: "PIXEL-V2"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "PIXEL-V2 Identification Kamelet"
    description: |-
      Redis-based reference data identification and caching kamelet for payment processing.
      Fetches flow configuration from Redis cache or referential service with automatic cache population.
    required:
      - flowCode
    type: object
    properties:
      flowCode:
        title: Flow Code
        description: The flow code to identify and retrieve configuration for
        type: string
        example: "PACS008"
      referentialServiceUrl:
        title: Referential Service URL
        description: Base URL of the referential service for flow configuration retrieval
        type: string
        default: "http://pixel-v2-referential:8099"
      kafkaBrokers:
        title: Kafka Brokers
        description: Kafka broker URLs for cache refresh messaging
        type: string
        default: "kafka:29092"
      cacheTtl:
        title: Cache TTL
        description: Cache time-to-live in seconds
        type: integer
        default: 3600
  dependencies:
    - "camel:kamelet"
    - "camel:log"
    - "camel:http"
    - "camel:jackson"
    - "camel:kafka"
  template:
    from:
      uri: "kamelet:source"
      steps:
        # Store original message body for preservation
        - setHeader:
            name: OriginalBody
            simple: "${body}"
        
        # Set cache key based on flow code
        - setHeader:
            name: CacheKey
            simple: "flow_config_{{flowCode}}"
        
        # Log event before identification
        
        - toD:
            uri: "kamelet:k-log-events?flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&kafkaTopicName=${header.KafkaLogTopicName}&brokers=${header.Brokers}&logMessageTxt=Start identification - flowOccurId: ${header.FlowOccurId}, FlowCode: {{flowCode}}&level=INFO"
            pattern: "InOnly"
        
        # Try to get from Redis cache
        - setHeader:
            name: RedisCommand
            constant: "GET"
        - to: "bean:redisProcessor"
        
        # Choose based on cache result
        - choice:
            when:
              - simple: "${body} == null"
                steps:
                  - log: 
                      message: "Cache MISS: Fetching flow config for {{flowCode}} from referential service"
                      loggingLevel: DEBUG
                  # Fetch from referential service
                  - doTry:
                      steps:
                        - log: 
                            message: "Original message body preserved: ${header.OriginalBody}"
                            loggingLevel: DEBUG
                        - setHeader:
                            name: CamelHttpMethod
                            constant: "GET"
                        - setHeader:
                            name: Content-Type
                            constant: "application/json"
                        - toD: "{{referentialServiceUrl}}/api/flows/referential/{{flowCode}}/complete?bridgeEndpoint=true"
                        - convertBodyTo: "java.lang.String"
                        - log: 
                            message: "Successfully retrieved flow config for {{flowCode}} from referential service"
                            loggingLevel: DEBUG
                        - setHeader:
                            name: FlowConfiguration
                            simple: "${body}"
                        - setHeader:
                            name: CacheKey
                            simple: "flow_config_{{flowCode}}"
                        - setHeader:
                            name: CacheTTL
                            constant: "{{cacheTtl}}"
                        - setBody:
                            simple: "${header.OriginalBody}"
                        - log: 
                            message: "Original message body restored before Redis SET: ${body}"
                            loggingLevel: DEBUG
                        # Cache the result
                        - setHeader:
                            name: RedisCommand
                            constant: "SETEX"
                        - to: "bean:redisProcessor"
                      doCatch:
                        - exception: "java.lang.Exception"
                          steps:
                            - log: 
                                message: "Failed to retrieve flow config for {{flowCode}} from referential service: ${exception.message}"
                                loggingLevel: DEBUG
                            - setBody:
                                constant: '{"error":"referential_service_unavailable","flowCode":"{{flowCode}}"}'
                            - setHeader:
                                name: FlowConfiguration
                                simple: "${body}"
                            - setBody:
                                simple: "${header.OriginalBody}"
            otherwise:
              steps:
                - log: 
                    message: "Cache HIT: Using cached flow config for {{flowCode}}"
                    loggingLevel: DEBUG
                
                - setHeader:
                    name: FlowConfiguration
                    simple: "${body}"
        
        # Restore original message body
        - setBody:
            simple: "${header.OriginalBody}"
        - removeHeader: "OriginalBody"
        
        # Log event after identification
        - toD:
            uri: "kamelet:k-log-events?flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&kafkaTopicName=${header.KafkaLogTopicName}&brokers=${header.Brokers}&logMessageTxt=End identification - flowOccurId: ${header.FlowOccurId}, FlowCode: {{flowCode}}&level=INFO"
            pattern: "InOnly"
        
        # Send to sink
        - to: "kamelet:sink"
