apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-mq-starter
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-MQ Starter"
    description: |-
      JMS Queue listener that processes messages and forwards to k-log-flow-summary
    required:
      - mqFileName
      - connectionFactory
    type: object
    properties:
      mqFileName:
        title: MQ File Name
        description: Name of the JMS queue to listen to
        type: string
      connectionFactory:
        title: Connection Factory
        description: JMS connection factory bean name
        type: string
        default: "jmsConnectionFactory"
      concurrentConsumers:
        title: Concurrent Consumers
        description: Number of concurrent consumers
        type: integer
        default: 1
      flowCode:
        title: Flow Code
        description: Flow processing code
        type: string
        default: "PACS008"
      messageType:
        title: Message Type
        description: Type of message being processed
        type: string
        default: "PACS008"
      kafkaFlowSummaryTopicName:
        title: Kafka  Flow Summary Topic Name
        description: Kafka topic for flow summary logs
        type: string
        default: "flow-summary"
      kafkaLogTopicName:
        title: Kafka  Log Topic Name
        description: Kafka topic for log events
        type: string
        default: "log-events"
      kafkaDistributionTopicName:
        title: Kafka  Distribution Topic Name
        description: Kafka topic for distribution logs
        type: string
        default: "distribution"
      sinkEndpoint:
        title: Sink Endpoint
        description: Endpoint where processed messages should be sent
        type: string
        default: "direct:pacs008-main-processing"
      brokers:
        title: Kafka Brokers
        description: Kafka brokers for flow summary
        type: string
        default: "pixel-v2-kafka:29092"
      flowCountryCode:
        title: Flow Country Code
        description: Country code for flow processing
        type: string
      flowCountryId:
        title: Flow Country ID
        description: Country ID for flow processing
        type: string
      dataSource:
        title: Data Source
        description: Database data source bean name for sequence generation
        type: string
        default: "dataSource"
  template:
    from:
      uri: "jms:queue:{{mqFileName}}?connectionFactory=#{{connectionFactory}}&concurrentConsumers={{concurrentConsumers}}"
      steps:
        - log:
            message: "[K-MQ-STARTER] - Message received from queue: {{mqFileName}}, MessageId: ${header.JMSMessageID}, CorrelationId: ${header.JMSCorrelationID}"
        - setHeader:
            name: "ReceivedTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSZ}"
        # Store original body before sequence generation
        - setHeader:
            name: "originalBody"
            simple: "${body}"
        # Generate unique flow occurrence ID from database sequence
        - to:
            uri: "sql:SELECT nextval('pixel_v2.flow_occurence_id_seq') as flowOccurId?dataSource=#dataSource"
        - setHeader:
            name: "flowOccurId"
            simple: "${body[0][flowOccurId]}"
        # Restore original body
        - setBody:
            simple: "${header.originalBody}"
        - removeHeader:
            name: "originalBody"
        - setHeader:
            name: "SourceQueue"
            simple: "{{mqFileName}}"
        - setHeader:
            name: "queueName"
            simple: "{{mqFileName}}"
        - setHeader:
            name: "flowCode"
            constant: "{{flowCode}}"
        - setHeader:
            name: "MessageType"
            constant: "{{messageType}}"
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSZ}"
        - setHeader:
            name: "step"
            constant: "IN_PROGRESS"
        - setHeader:
            name: "brokers"
            constant: "{{brokers}}"
        - setHeader:
            name: "kafkaFlowSummaryTopicName"
            constant: "{{kafkaFlowSummaryTopicName}}"
        - setHeader:
            name: "kafkaLogTopicName"
            constant: "{{kafkaLogTopicName}}"
        - setHeader:
            name: "kafkaDistributionTopicName"
            constant: "{{kafkaDistributionTopicName}}"
        - setHeader:
            name: "flowCountryCode"
            simple: "{{flowCountryCode}}"
        - setHeader:
            name: "flowCountryId"
            simple: "{{flowCountryId}}"
        - setHeader:
            name: "MessageId"
            simple: "${header.JMSMessageID}"
        - setHeader:
            name: "CorrelationId"
            simple: "${header.JMSCorrelationID}"
        - setHeader:
            name: "beginFlowDatetime"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}"
        - setHeader:
            name: "beginFlowDate"
            simple: "${date:now:yyyy-MM-dd}"
        # Set charset with proper fallback
        - choice:
            when:
              - simple: "${header.JMS_IBM_CHARACTER_SET} != null && ${header.JMS_IBM_CHARACTER_SET} != ''"
                steps:
                  - setHeader:
                      name: "JMSEncoding" 
                      simple: "${header.JMS_IBM_CHARACTER_SET}"
            otherwise:
              steps:
                - setHeader:
                    name: "JMSEncoding"
                    constant: "utf-8"
        # Archive flowOccurId and timestamp
        - toD:
            uri: "file:/opt/in?fileName=${header.flowCode}_${header.flowOccurId}_${date:now:yyyyMMddHHmmssSSS}.txt&charset=${header.JMSEncoding}"
        
        
        - wireTap:
            uri: "kamelet:k-log-flow-summary"
            parameters:
              step: "${header.step}"
              kafkaTopicName: "${header.kafkaFlowSummaryTopicName}"
              brokers: "{{brokers}}"
        - log:
            message: "[K-MQ-STARTER] - Processing completed for message from queue: {{mqFileName}}, flowOccurId: ${header.flowOccurId}"
        - to: "{{sinkEndpoint}}"