apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-mq-starter
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-MQ Starter"
    description: |-
      JMS Queue listener that processes messages and forwards to k-log-flow-summary
    required:
      - mqFileName
      - connectionFactory
      - nasArchiveUrl
      - flowCountryCode
      - flowCountryId
      - dataSource
    type: object
    properties:
      mqFileName:
        title: MQ File Name
        description: Name of the JMS queue to listen to
        type: string
      connectionFactory:
        title: Connection Factory
        description: JMS connection factory bean name
        type: string
        default: "jmsConnectionFactory"
      concurrentConsumers:
        title: Concurrent Consumers
        description: Number of concurrent consumers
        type: integer
        default: 1
      flowCode:
        title: Flow Code
        description: Flow processing code
        type: string
        default: "PACS008"
      messageType:
        title: Message Type
        description: Type of message being processed
        type: string
        default: "PACS008"
      kafkaFlowSummaryTopicName:
        title: Kafka  Flow Summary Topic Name
        description: Kafka topic for flow summary logs
        type: string
        default: "flow-summary"
      kafkaLogTopicName:
        title: Kafka  Log Topic Name
        description: Kafka topic for log events
        type: string
        default: "log-events"
      kafkaDistributionTopicName:
        title: Kafka  Distribution Topic Name
        description: Kafka topic for distribution logs
        type: string
        default: "distribution"
      brokers:
        title: Kafka Brokers
        description: Kafka brokers for flow summary
        type: string
        default: "pixel-v2-kafka:29092"
      flowCountryCode:
        title: Flow Country Code
        description: Country code for flow processing
        type: string
      flowCountryId:
        title: Flow Country ID
        description: Country ID for flow processing
        type: string
      dataSource:
        title: Data Source
        description: Database data source bean name for sequence generation
        type: string
        default: "dataSource"
      nasArchiveUrl:
        title: NAS Archive URL
        description: File URL for archiving messages to NAS (mounted directory)
        type: string
  dependencies:
    - "camel:jms"
    - "camel:sql"
    - "camel:file"
    - "camel:kamelet"
  template:
    from:
      uri: "jms:queue:{{mqFileName}}?connectionFactory=#{{connectionFactory}}&concurrentConsumers={{concurrentConsumers}}"
      steps:
        # - log:
        #     message: "[K-MQ-STARTER] - Message received from queue: {{mqFileName}}, MessageId: ${header.JMSMessageID}, CorrelationId: ${header.JMSCorrelationID}"
        - setHeader:
            name: "ReceivedTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSZ}"
        
        # Log event before starting MQ processing
        - setHeader:
            name: "CamelKameletFlowId"
            simple: "${date:now:yyyyMMddHHmmssSSS}"
        - toD:
            uri: "kamelet:k-log-events?flowId=${header.CamelKameletFlowId}&kafkaTopicName={{kafkaLogTopicName}}&brokers={{brokers}}&logMessageTxt=Start MQ processing - queue: {{mqFileName}}, MessageId: ${header.JMSMessageID}&level=INFO"
            pattern: "InOnly"
        
        # Store original body before sequence generation
        - setHeader:
            name: "originalBody"
            simple: "${body}"
        # Generate unique flow occurrence ID from database sequence
        - to:
            uri: "sql:SELECT nextval('pixel_v2.flow_occurence_id_seq') as flowOccurId?dataSource=#dataSource"
        - setHeader:
            name: "flowOccurId"
            simple: "${body[0][flowOccurId]}"
        # Restore original body
        - setBody:
            simple: "${header.originalBody}"
        - removeHeader:
            name: "originalBody"
        - setHeader:
            name: "SourceQueue"
            simple: "{{mqFileName}}"
        - setHeader:
            name: "queueName"
            simple: "{{mqFileName}}"
        - setHeader:
            name: "flowCode"
            constant: "{{flowCode}}"
        - setHeader:
            name: "MessageType"
            constant: "{{messageType}}"
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSZ}"
        - setHeader:
            name: "step"
            constant: "IN_PROGRESS"
        - setHeader:
            name: "brokers"
            constant: "{{brokers}}"
        - setHeader:
            name: "kafkaFlowSummaryTopicName"
            constant: "{{kafkaFlowSummaryTopicName}}"
        - setHeader:
            name: "kafkaLogTopicName"
            constant: "{{kafkaLogTopicName}}"
        - setHeader:
            name: "kafkaDistributionTopicName"
            constant: "{{kafkaDistributionTopicName}}"
        - setHeader:
            name: "flowCountryCode"
            simple: "{{flowCountryCode}}"
        - setHeader:
            name: "flowCountryId"
            simple: "{{flowCountryId}}"
        - setHeader:
            name: "MessageId"
            simple: "${header.JMSMessageID}"
        - setHeader:
            name: "CorrelationId"
            simple: "${header.JMSCorrelationID}"
        - setHeader:
            name: "beginFlowDatetime"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}"
        - setHeader:
            name: "beginFlowDate"
            simple: "${date:now:yyyy-MM-dd}"
        - setHeader:
            name: "nasArchiveUrl"
            simple: "{{nasArchiveUrl}}"
        # Set charset with proper fallback
        - choice:
            when:
              - simple: "${header.JMS_IBM_CHARACTER_SET} != null && ${header.JMS_IBM_CHARACTER_SET} != ''"
                steps:
                  - setHeader:
                      name: "JMSEncoding" 
                      simple: "${header.JMS_IBM_CHARACTER_SET}"
            otherwise:
              steps:
                - setHeader:
                    name: "JMSEncoding"
                    constant: "utf-8"
        # # Log event before save to NAS
        # - to:
        #     uri: "kamelet:k-log-events?flowId=${uuid}-start&kafkaTopicName=${header.kafkaLogTopicName}&brokers=${header.brokers}&logMessageTxt=Start receipt occurrence - flowOccurId: ${header.flowOccurId}&level=INFO"
              
        # Archive flowOccurId and timestamp to NAS
        # Store original body before file operation
        - setHeader:
            name: "originalBodyBeforeArchive"
            simple: "${body}"
        - toD:
            uri: "${header.nasArchiveUrl}/IN/${header.flowOccurId}/?fileName=${header.flowCode}_${header.flowOccurId}_${date:now:yyyyMMddHHmmssSSS}.txt&autoCreate=true&tempPrefix=.tmp"
        # Restore original body after file operation
        - setBody:
            simple: "${header.originalBodyBeforeArchive}"
        - removeHeader:
            name: "originalBodyBeforeArchive"
        
        - wireTap:
            uri: "kamelet:k-log-flow-summary?step=${header.step}&kafkaTopicName=${header.kafkaFlowSummaryTopicName}&brokers=${header.brokers}"
        
        # Log event after completing MQ processing
        - setHeader:
            name: "CamelKameletFlowId"
            simple: "${date:now:yyyyMMddHHmmssSSS}"
        - toD:
            uri: "kamelet:k-log-events?flowId=${header.CamelKameletFlowId}&kafkaTopicName={{kafkaLogTopicName}}&brokers={{brokers}}&logMessageTxt=End MQ processing - queue: {{mqFileName}}, flowOccurId: ${header.flowOccurId}, archived to: ${header.nasArchiveUrl}/IN/${header.flowOccurId}/&level=INFO"
            pattern: "InOnly"
        
        - to: "kamelet:sink"