apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: k-cft-starter
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-CFT Message Receiver"
    description: "Monitors NAS folder for new files, reads XML payment messages line by line, logs receipt details, and routes messages for further processing"
    required: [directoryPath]
    properties:
      directoryPath:
        title: "NAS Directory Path"
        type: string
        default: "/nas/incoming"
      filePattern:
        title: "File Pattern"
        type: string
        default: ".*\\.xml"
      processedDirectory:
        title: "Processed files directory"
        type: string
        default: "/nas/processed"
      errorDirectory:
        title: "Error files directory"
        type: string
        default: "/nas/error"
      delay:
        title: "Polling delay in milliseconds"
        type: integer
        default: 5000
  template:
    from:
      uri: "file:{{directoryPath}}"
      parameters:
        include: "{{filePattern}}"
        delay: "{{delay}}"
        move: "{{processedDirectory}}"
        moveFailed: "{{errorDirectory}}"
        readLock: "changed"
        readLockTimeout: "10000"
      steps:
        - log: 
            message: "[CFT-RECEIVER] Starting to process file: ${header.FileName} from {{directoryPath}}"
            loggingLevel: "INFO"
        
        - setHeader:
            name: "OriginalFileName"
            simple: "${header.FileName}"
        
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}"
        
        - split:
            tokenize: "\n"
            streaming: true
            steps:
              - filter:
                  simple: "${body} != null && ${body.trim()} != ''"
                  steps:
                    - log: 
                        message: "[CFT-RECEIVER] Processing XML message line ${header.CamelSplitIndex} from file ${header.OriginalFileName}: ${body}"
                        loggingLevel: "DEBUG"
                    
                    - setHeader:
                        name: "MessageSource"
                        constant: "CFT_FILE"
                    
                    - setHeader:
                        name: "ProcessingLineTimestamp"
                        simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}"
                    
                    - setHeader:
                        name: "ReceiptChannel"
                        constant: "FILE_CFT"
                    
                    - setHeader:
                        name: "FileName"
                        simple: "${header.OriginalFileName}"
                    
                    - setHeader:
                        name: "LineNumber"
                        simple: "${header.CamelSplitIndex}"
                    
                    - setHeader:
                        name: "DirectoryPath"
                        simple: "{{directoryPath}}"
                    
                    - log: 
                        message: "[CFT-RECEIVER] Message metadata set - Source: ${header.MessageSource}, File: ${header.FileName}, Line: ${header.LineNumber}, Timestamp: ${header.ProcessingLineTimestamp}"
                        loggingLevel: "DEBUG"
        
        - log: 
            message: "[CFT-RECEIVER] Completed processing file: ${header.OriginalFileName} - Processing started at ${header.ProcessingTimestamp}"
            loggingLevel: "INFO"