apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: k-cft-starter
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-CFT Message Receiver"
    description: "Monitors NAS folder for new files, reads XML payment messages line by line, logs receipt details, and routes messages for further processing"
    required: [directoryPath]
    properties:
      directoryPath:
        title: "NAS Directory Path"
        type: string
        default: "/nas/incoming"
      filePattern:
        title: "File Pattern"
        type: string
        default: ".*\\.xml"
      processedDirectory:
        title: "Processed files directory"
        type: string
        default: "/nas/processed"
      errorDirectory:
        title: "Error files directory"
        type: string
        default: "/nas/error"
      delay:
        title: "Polling delay in milliseconds"
        type: integer
        default: 5000
  template:
    from:
      uri: "file:{{directoryPath}}"
      parameters:
        include: "{{filePattern}}"
        delay: "{{delay}}"
        move: "{{processedDirectory}}"
        moveFailed: "{{errorDirectory}}"
        readLock: "changed"
        readLockTimeout: "10000"
      steps:
        - log: 
            message: "[CFT-RECEIVER] Starting to process file: ${header.CamelFileName} from {{directoryPath}}"
            loggingLevel: "INFO"
        
        - set-header:
            name: "originalFileName"
            simple: "${header.CamelFileName}"
        
        - set-header:
            name: "fileProcessingStartTime"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}"
        
        - split:
            tokenize: "\n"
            streaming: true
            steps:
              - filter:
                  simple: "${body} != null && ${body.trim()} != ''"
                  steps:
                    - log: 
                        message: "[CFT-RECEIVER] Processing XML message line ${header.CamelSplitIndex} from file ${header.originalFileName}: ${body}"
                        loggingLevel: "DEBUG"
                    
                    - set-header:
                        name: "messageSource"
                        constant: "CFT_FILE"
                    
                    - set-header:
                        name: "receiptTimestamp"
                        simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}"
                    
                    - set-header:
                        name: "receiptChannel"
                        constant: "FILE_CFT"
                    
                    - set-header:
                        name: "fileName"
                        simple: "${header.originalFileName}"
                    
                    - set-header:
                        name: "lineNumber"
                        simple: "${header.CamelSplitIndex}"
                    
                    - set-header:
                        name: "directoryPath"
                        simple: "{{directoryPath}}"
                    
                    - log: 
                        message: "[CFT-RECEIVER] Message metadata set - Source: ${header.messageSource}, File: ${header.fileName}, Line: ${header.lineNumber}, Timestamp: ${header.receiptTimestamp}"
                        loggingLevel: "DEBUG"
        
        - log: 
            message: "[CFT-RECEIVER] Completed processing file: ${header.originalFileName} - Processing started at ${header.fileProcessingStartTime}"
            loggingLevel: "INFO"