apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-referentiel-data-loader
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "K-Referentiel Data Loader"
    description: "Loads FlowReference configuration from external REST service and returns JSON data structured like FlowReference entity."
    required: [serviceUrl, flowCode]
    properties:
      serviceUrl:
        title: "Service URL"
        description: "The HTTP endpoint used to retrieve FlowReference configuration."
        type: string
        default: "http://localhost:8099"
      flowCode:
        title: "Flow Code"
        description: "The flow code identifier to retrieve specific FlowReference configuration (e.g., PACS008, PACS009, PAIN001, CAMT053)"
        type: string
        example: "PACS008"
      configEndpoint:
        title: "Configuration Endpoint Path"
        description: "Path to append to serviceUrl for FlowReference retrieval (e.g., /api/flows)"
        type: string
        default: "/api/flows"
  template:
    from:
      uri: "kamelet:source"
      steps:
        - log: "Loading FlowReference configuration for flowCode: {{flowCode}} from service: {{serviceUrl}}"
        
        # Store original message body
        - set-header:
            name: "OriginalBody"
            simple: "${body}"
        
        # Set context headers for processor
        - set-header:
            name: "FlowCode"
            simple: "{{flowCode}}"
        - set-header:
            name: "ServiceUrl"
            simple: "{{serviceUrl}}"
        
        # Prepare HTTP request
        - log: "Calling FlowReference API: {{serviceUrl}}{{configEndpoint}}/{{flowCode}}"
        - set-header:
            name: "CamelHttpMethod"
            constant: "GET"
        - set-header:
            name: "Accept"
            constant: "application/json"
        - set-header:
            name: "User-Agent"
            constant: "Camel-Http/4.1.0"
        - remove-header:
            name: "Content-Type"
        
        # Clear body for GET request
        - set-body:
            constant: null
        
        # Call external service to get FlowReference
        - to: "{{serviceUrl}}{{configEndpoint}}/{{flowCode}}?throwExceptionOnFailure=false"
        
        # Log response
        - log: "FlowReference API Response - Status: ${header.CamelHttpResponseCode}, Body: ${body}"
        
        # Process FlowReference response
        - process:
            ref: "flowReferenceProcessor"
        
        # Log completion
        - log: "FlowReference processing completed - Loaded: ${header.FlowReferenceLoaded}, FlowCode: {{flowCode}}"
        
        # Preserve original message for downstream processing
        - set-header:
            name: "FlowReferenceData"
            simple: "${body}"
        - set-body:
            simple: "${header.OriginalBody}"
        - remove-header:
            name: "OriginalBody"
        
        # Final log with key headers
        - log: "FlowReference enrichment completed - FlowId: ${header.FlowId}, Status: ${header.FlowStatus}, RailMode: ${header.RailMode}"
        
        - to: "kamelet:sink"
