CREATE TABLE FLOW_REFERENCE (

  FLOW_ID VARCHAR(36) PRIMARY KEY,

  FLOW_CODE VARCHAR(50) NOT NULL,

  FLOW_NAME VARCHAR(100) NOT NULL,

  STATUS VARCHAR(10) CHECK (STATUS IN ('ACTIVE', 'DISABLED')),

  SOURCE_CHANNEL VARCHAR(20),

  SOURCE_SYSTEM VARCHAR(50),

  SOURCE_FORMAT VARCHAR(20),

  FLOW_TYPE VARCHAR(20),

  RAIL_MODE VARCHAR(10),

  SLA_MAX_LATENCY_MS INTEGER,

  PRIORITY INTEGER,

  SPLIT_ENABLED VARCHAR(5) CHECK (SPLIT_ENABLED IN ('TRUE', 'FALSE')),

  SPLIT_CHUNK_SIZE INTEGER,

  CONCAT_ENABLED VARCHAR(5) CHECK (CONCAT_ENABLED IN ('TRUE', 'FALSE')),

  CONCAT_CRITERIA VARCHAR(20),

  TARGET_SYSTEM VARCHAR(20),

  TARGET_CHANNEL VARCHAR(20),

  RETENTION_IN_ENABLED VARCHAR(5) CHECK (RETENTION_IN_ENABLED IN ('TRUE', 'FALSE')),

  RETENTION_IN_MODE VARCHAR(10),

  RETENTION_IN_DAYS INTEGER,

  RETENTION_IN_RELEASE_DATE DATE,

  RETENTION_IN_STORAGE_PATH VARCHAR(100),

  RETENTION_OUT_ENABLED VARCHAR(5) CHECK (RETENTION_OUT_ENABLED IN ('TRUE', 'FALSE')),

  RETENTION_OUT_MODE VARCHAR(10),

  RETENTION_OUT_DAYS INTEGER,

  RETENTION_OUT_RELEASE_DATE DATE,

  RETENTION_OUT_STORAGE_PATH VARCHAR(100),

  SHAPING_ENABLED VARCHAR(5) CHECK (SHAPING_ENABLED IN ('TRUE', 'FALSE')),

  SHAPING_MAX_TRX_PER_MIN INTEGER,

  SHAPING_STRATEGY VARCHAR(10),

  PII_LEVEL VARCHAR(10),

  ENCRYPTION_REQUIRED VARCHAR(5) CHECK (ENCRYPTION_REQUIRED IN ('TRUE', 'FALSE')),

  DR_STRATEGY VARCHAR(20),

  LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  VERSION VARCHAR(10),

  COMMENTS VARCHAR(200)

);
 
CREATE TABLE LOG_EVENT (

	LOGID VARCHAR(64) NOT NULL, 

	DATATS TIMESTAMP(6) NOT NULL, 

	FLOWID VARCHAR(64) NOT NULL, 

	HALFFLOWID VARCHAR(64) NOT NULL, 

	FLOWCODE VARCHAR(64) NOT NULL, 

	HALFFLOWCODE VARCHAR(64) NOT NULL, 

	CONTEXTID VARCHAR(64), 

	CLIENTLOGTIMESTAMP TIMESTAMP(6) NOT NULL, 

	DBLOGTIMESTAMP TIMESTAMP(6) NOT NULL, 

	TXT VARCHAR(2048) NOT NULL, 

	LONGTXT TEXT, 

	LOGROLE VARCHAR(16) NOT NULL, 

	CODE VARCHAR(32), 

	CUSTOMSTEP VARCHAR(128), 

	COMPONENT VARCHAR(64) NOT NULL, 

	INSTANCEID VARCHAR(16) NOT NULL, 

	SERVICEPATH VARCHAR(512), 

	PROCESSPATH VARCHAR(512), 

	REFFLOWID DECIMAL(10,0), 

	BEGINPROCESS TIMESTAMP(6), 

	ENDPROCESS TIMESTAMP(6), 

	CONTEXTTIMESTAMP TIMESTAMP(6), 

	MSGSENTTIMESTAMP TIMESTAMP(6), 

	MESSAGINGTYPE VARCHAR(10), 

	MSGID VARCHAR(64), 

	MSGPRIORITY INTEGER, 

	MSGCORRELATIONID VARCHAR(256), 

	MSGSOURCESYSTEM VARCHAR(128), 

	MSGPRIVATECONTEXT TEXT, 

	MSGTRANSACTIONID VARCHAR(64), 

	MSGPROPERTIES TEXT, 

	MSGBATCHNAME VARCHAR(256), 

	MSGBATCHMSGNO INTEGER, 

	MSGBATCHSIZE INTEGER, 

	XMLMSGACTION VARCHAR(256), 

	MSGRESUBMITIND VARCHAR(64), 

	MSGBODY TEXT, 

	LOG_DAY DATE GENERATED ALWAYS AS (DATE_TRUNC('day', DATATS)) STORED 

);
 
CREATE TABLE FLOW_SUMMARY (

	FLOW_OCCUR_ID VARCHAR(64), 

	FLOW_CODE VARCHAR(64), 

	FLOW_STATUS_CODE VARCHAR(20), 

	FLOW_COUNTRY_CODE VARCHAR(59), 

	FLOW_COUNTRY_ID INTEGER, 

	FLOW_TYPE_ID INTEGER, 

	FLOW_COMMENT VARCHAR(255), 

	NB_OUT_EXPECTED INTEGER, 

	NB_OUT_COMPLETED INTEGER, 

	NB_ERROR INTEGER, 

	NB_REMITANCE INTEGER, 

	NB_TRANSACTION INTEGER, 

	NB_REPLAY INTEGER, 

	ISSUING_PARTNER_CODE VARCHAR(64), 

	ISSUING_PARTNER_LINK VARCHAR(128), 

	RECIPIENT_PARTNER_CODE VARCHAR(255), 

	RECIPIENT_PARTNER_LINK VARCHAR(510), 

	LAST_LOG_ID VARCHAR(64), 

	LAST_LOG_COMPONENT VARCHAR(255), 

	LAST_LOG_DATETIME TIMESTAMP(6), 

	LAST_LOG_STATUS_CODE VARCHAR(20), 

	LAST_UPDATE_DATETIME TIMESTAMP(6), 

	LAST_UPDATE_USER VARCHAR(50), 

	ROOT_ERROR_CODE VARCHAR(50), 

	ROOT_ERROR_LOG_ID VARCHAR(50), 

	ROOT_ERROR_DATETIME TIMESTAMP(6), 

	INPUT_FILE_PATH VARCHAR(500), 

	INPUT_FILE_SIZE VARCHAR(50), 

	REF_FLOW_ID DECIMAL(10,0), 

	BEGIN_FLOW_DATETIME TIMESTAMP(6), 

	END_FLOW_DATETIME TIMESTAMP(6), 

	CURRENT_CLIENT_DATETIME TIMESTAMP(6), 

	BEGIN_FLOW_DATE DATE GENERATED ALWAYS AS (DATE_TRUNC('day', BEGIN_FLOW_DATETIME)) STORED, 

	END_FLOW_DATE DATE GENERATED ALWAYS AS (DATE_TRUNC('day', END_FLOW_DATETIME)) STORED, 

	LAST_UPDATE_DATE DATE GENERATED ALWAYS AS (DATE_TRUNC('day', LAST_UPDATE_DATETIME)) STORED, 

	REPLAY_ID VARCHAR(20), 

	REGION VARCHAR(5)

);
 
CREATE TABLE PAYMENT_AUDIT_DETAILS (

	PAYMENT_AUDIT_ID DECIMAL(20,0), 

	FLOW_OCCUR_ID VARCHAR(64) NOT NULL, 

	DATATS TIMESTAMP(6) NOT NULL, 

	AMOUNT DECIMAL, 

	CURRENCY VARCHAR(3), 

	DEBTOR_ACCOUNT VARCHAR(140), 

	DEBTOR_NAME VARCHAR(140), 

	CREDITOR_ACCOUNT VARCHAR(140), 

	CREDITOR_NAME VARCHAR(140), 

	CREDITOR_BANK VARCHAR(140), 

	PAYMENT_REF VARCHAR(140), 

	IS_VIRTUAL CHAR(1), 

	VIRTUAL_ACCOUNT VARCHAR(35), 

	MESSAGE_TYPE VARCHAR(140), 

	RECIPIENT_PARTNER VARCHAR(20), 

	LOG_DAY DATE, 

	MESSAGE_USER_REFERENCE VARCHAR(16), 

	COUNTRY VARCHAR(20), 

	SENDER VARCHAR(35), 

	DEBTOR_BANK VARCHAR(70), 

	MESSAGE_ID VARCHAR(35), 

	REQUESTED_EXECUTION_DATE DATE, 

	UETR VARCHAR(36), 

	REGION VARCHAR(5)

);
 