apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-http-starter
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-HTTP Starter"
    description: |-
      HTTP Endpoint listener that processes messages
    required:
      - httpPath
      - nasArchiveUrl
      - flowCountryCode
      - flowCountryId
      - dataSource
    type: object
    properties:
      httpPath:
        title: HTTP Path
        description: HTTP endpoint path to listen on
        type: string
      httpPort:
        title: HTTP Port
        description: HTTP port to listen on
        type: integer
        default: 8080
      httpMethod:
        title: HTTP Method
        description: HTTP method to accept (GET, POST, PUT, etc.)
        type: string
        default: "POST"
      flowCode:
        title: Flow Code
        description: Flow processing code
        type: string
        default: "PACS008"
      messageType:
        title: Message Type
        description: Type of message being processed
        type: string
        default: "PACS008"
      kafkaFlowSummaryTopicName:
        title: Kafka Flow Summary Topic Name
        description: Kafka topic for flow summary logs
        type: string
        default: "flow-summary"
      kafkaLogTopicName:
        title: Kafka Log Topic Name
        description: Kafka topic for log events
        type: string
        default: "log-events"
      kafkaDistributionTopicName:
        title: Kafka Distribution Topic Name
        description: Kafka topic for distribution logs
        type: string
        default: "distribution"
      brokers:
        title: Kafka Brokers
        description: Kafka brokers for flow summary
        type: string
        default: "pixel-v2-kafka:29092"
      flowCountryCode:
        title: Flow Country Code
        description: Country code for flow processing
        type: string
      flowCountryId:
        title: Flow Country ID
        description: Country ID for flow processing
        type: string
      dataSource:
        title: Data Source
        description: Database data source bean name for sequence generation
        type: string
        default: "dataSource"
      nasArchiveUrl:
        title: NAS Archive URL
        description: File URL for archiving messages to NAS (mounted directory)
        type: string
  dependencies:
    - "camel:http"
    - "camel:jetty"
    - "camel:sql"
    - "camel:file"
    - "camel:kamelet"
  template:
    from:
      uri: "jetty:http://0.0.0.0:{{httpPort}}{{httpPath}}?httpMethodRestrict={{httpMethod}}"
      steps:
        - setHeader:
            name: "ReceivedTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}"
        
        # Log event before starting HTTP processing
        - setHeader:
            name: "CamelKameletFlowId"
            simple: "${date:now:yyyyMMddHHmmssSSS}"
        - toD:
            uri: "kamelet:k-log-events?flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&kafkaTopicName=${header.KafkaLogTopicName}&brokers=${header.Brokers}&logMessageTxt=Start HTTP processing - path: {{httpPath}}, method: {{httpMethod}}, RemoteAddress: ${header.CamelHttpRemoteAddress}&level=INFO"
            pattern: "InOnly"
        
        # Store original body before sequence generation
        - setHeader:
            name: "OriginalBody"
            simple: "${body}"
        # Generate unique flow occurrence ID from database sequence
        - to:
            uri: "sql:SELECT nextval('pixel_v2.flow_occurence_id_seq') as flowOccurId?dataSource=#dataSource"
        - setHeader:
            name: "FlowOccurId"
            simple: "${body[0][flowOccurId]}"
        # Restore original body
        - setBody:
            simple: "${header.OriginalBody}"
        - removeHeader:
            name: "OriginalBody"
        - setHeader:
            name: "SourceEndpoint"
            simple: "{{httpPath}}"
        - setHeader:
            name: "HttpPath"
            simple: "{{httpPath}}"
        - setHeader:
            name: "FlowCode"
            constant: "{{flowCode}}"
        - setHeader:
            name: "MessageType"
            constant: "{{messageType}}"
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}"
        - setHeader:
            name: "Step"
            constant: "IN_PROGRESS"
        - setHeader:
            name: "Brokers"
            constant: "{{brokers}}"
        - setHeader:
            name: "kafkaFlowSummaryTopicName"
            constant: "{{kafkaFlowSummaryTopicName}}"
        - setHeader:
            name: "kafkaLogTopicName"
            constant: "{{kafkaLogTopicName}}"
        - setHeader:
            name: "kafkaDistributionTopicName"
            constant: "{{kafkaDistributionTopicName}}"
        - setHeader:
            name: "FlowCountryCode"
            simple: "{{flowCountryCode}}"
        - setHeader:
            name: "FlowCountryId"
            simple: "{{flowCountryId}}"
        - setHeader:
            name: "MessageId"
            simple: "${header.CamelHttpRemoteAddress}-${header.flowOccurId}"
        - setHeader:
            name: "CorrelationId"
            simple: "${header.CamelHttpUri}-${date:now:yyyyMMddHHmmssSSS}"
        - setHeader:
            name: "BeginFlowDatetime"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}"
        - setHeader:
            name: "BeginFlowDate"
            simple: "${date:now:yyyy-MM-dd}"
        - setHeader:
            name: "NasArchiveUrl"
            simple: "{{nasArchiveUrl}}"
        # Set charset with proper fallback for HTTP
        - choice:
            when:
              - simple: "${header.Content-Type} != null && ${header.Content-Type} contains 'charset'"
                steps:
                  - setHeader:
                      name: "HttpEncoding" 
                      simple: "${header.Content-Type}"
            otherwise:
              steps:
                - setHeader:
                    name: "HttpEncoding"
                    constant: "utf-8"
              
        # Archive flowOccurId and timestamp to NAS
        # Store original body before file operation
        - setHeader:
            name: "OriginalBody"
            simple: "${body}"
        - toD:
            uri: "${header.NasArchiveUrl}/IN/${header.FlowOccurId}/?fileName=${header.FlowCode}_${header.FlowOccurId}_${date:now:yyyyMMddHHmmssSSS}.txt&autoCreate=true&tempPrefix=.tmp"
        # Restore original body after file operation
        - setBody:
            simple: "${header.OriginalBody}"
        - removeHeader:
            name: "OriginalBody"
        
        - wireTap:
            uri: "kamelet:k-log-flow-summary?step=${header.Step}&kafkaTopicName=${header.kafkaFlowSummaryTopicName}&brokers=${header.Brokers}"
        
        # Log event after completing HTTP processing
        - setHeader:
            name: "CamelKameletFlowId"
            simple: "${date:now:yyyyMMddHHmmssSSS}"
        - toD:
            uri: "kamelet:k-log-events?flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&kafkaTopicName=${header.KafkaLogTopicName}&brokers=${header.Brokers}&logMessageTxt=End HTTP processing - path: {{httpPath}}, flowOccurId: ${header.FlowOccurId}, archived to: ${header.NasArchiveUrl}/IN/${header.FlowOccurId}/&level=INFO"
            pattern: "InOnly"
        
        # Set HTTP response status
        - setHeader:
            name: "CamelHttpResponseCode"
            constant: "200"
        - setBody:
            constant: "{\"status\":\"success\",\"flowOccurId\":\"${header.flowOccurId}\",\"timestamp\":\"${header.ProcessingTimestamp}\"}"
        
        - to: "kamelet:sink"
        
        - set-header:
            name: "receiptChannel"
            constant: "REST_API"
        
        - set-header:
            name: "apiPath"
            simple: "{{path}}"
        
        - set-header:
            name: "httpMethod"
            simple: "${header.CamelHttpMethod}"
        
        - log: 
            message: "[HTTP-RECEIVER] Message metadata set - Source: ${header.messageSource}, Timestamp: ${header.receiptTimestamp}, Path: ${header.apiPath}, Method: ${header.httpMethod}"
            loggingLevel: "DEBUG"
        
        - set-body:
            constant: '{"status": "received", "message": "Message received and routed for processing", "timestamp": "${header.receiptTimestamp}"}'