apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-cft-publisher
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "K-CFT Publisher"
    description: |-
      CFT File Publisher that writes XML payment files to CFT directory.
      Publishes collection of XML payment files from a flowCode to CFT system.
    required:
      - directoryPath
      - flowCode
      - flowId
      - dataSource
    type: object
    properties:
      directoryPath:
        title: CFT Directory Path
        description: Target directory path for CFT files
        type: string
        default: "/nas/outgoing/cft"
      flowCode:
        title: Flow Code
        description: Flow processing code for file naming
        type: string
      flowId:
        title: Flow ID
        description: Unique flow identifier for tracking
        type: string
      dataSource:
        title: Data Source
        description: Database data source bean name for logging
        type: string
        default: "dataSource"
      filePrefix:
        title: File Prefix
        description: Prefix for generated CFT files
        type: string
        default: "CFT"
      fileExtension:
        title: File Extension
        description: File extension for generated files
        type: string
        default: ".xml"
      tempPrefix:
        title: Temporary File Prefix
        description: Prefix for temporary files during write
        type: string
        default: ".tmp"
      brokers:
        title: Kafka Brokers
        description: Kafka brokers for logging events
        type: string
        default: "pixel-v2-kafka:29092"
      kafkaLogTopicName:
        title: Kafka Log Topic Name
        description: Kafka topic for log events
        type: string
        default: "log-events"
  dependencies:
    - "camel:file"
    - "camel:sql"
    - "camel:kamelet"
  template:
    from:
      uri: "kamelet:source"
      steps:
        # Log event before publishing to CFT
        - toD:
            uri: "kamelet:k-log-events?flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&kafkaTopicName=${header.KafkaLogTopicName}&brokers=${header.Brokers}&logMessageTxt=Start CFT publishing - flowCode: ${header.FlowCode}, directory: ${header.CftDirectory}&level=INFO"
            pattern: "InOnly"
        
        # Set publishing metadata
        - setHeader:
            name: "flowCode"
            simple: "{{flowCode}}"
        - setHeader:
            name: "flowId"
            simple: "{{flowId}}"
        - setHeader:
            name: "publishTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}"
        - setHeader:
            name: "cftDirectory"
            simple: "{{directoryPath}}"
        
        # Generate unique filename
        - setHeader:
            name: "FileName"
            simple: "{{filePrefix}}_{{flowCode}}_${date:now:yyyyMMddHHmmssSSS}{{fileExtension}}"
        
        # Store original body before file operation
        - setHeader:
            name: "OriginalBody"
            simple: "${body}"
        
        # Write to CFT directory with temporary file
        - toD:
            uri: "{{directoryPath}}?fileName=${header.FileName}&autoCreate=true&tempPrefix={{tempPrefix}}"
        
        # Restore original body after file operation
        - setBody:
            simple: "${header.OriginalBody}"
        - removeHeader:
            name: "OriginalBody"
        
        # Set response headers with file details
        - setHeader:
            name: "CftFileName"
            simple: "${header.FileName}"
        - setHeader:
            name: "CftFilePath"
            simple: "{{directoryPath}}/${header.FileName}"
        - setHeader:
            name: "CftPublishStatus"
            constant: "SUCCESS"
        
        # Log event after successful publishing
        - toD:
            uri: "kamelet:k-log-events?flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&kafkaTopicName=${header.KafkaLogTopicName}&brokers=${header.Brokers}&logMessageTxt=End CFT publishing - flowCode: ${header.FlowCode}, file: ${header.FileName}, path: ${header.CftDirectory}/${header.FileName}&level=INFO"
            pattern: "InOnly"