apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-db-tx-messages
  labels:
    camel.apache.org/kamelet.type: "sink"
    pixel.v2/category: "persistence"
    pixel.v2/version: "1.0.0"
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "4.1.0"
    camel.apache.org/provider: "Pixel V2"
    pixel.v2/description: "database persistence using SQL component instead of JPA"
spec:
    definition:
      title: "Database Transaction"
      description: |
        Persists payment messages to database using SQL component for JBang compatibility.
        Avoids JPA class loading issues in containerized environments.
        Uses direct SQL INSERT with proper error handling and transaction support.
      required: []
      properties:
        messageId:
          title: "Message ID"
          description: "Unique identifier for the message"
          type: string
          default: "${header.MessageId}"
        correlationId:
          title: "Correlation ID"
          description: "Correlation identifier for the message"
          type: string
          default: "${header.CorrelationId}"
        messageType:
          title: "Message Type"
          description: "Type of the message (e.g., PACS008, CAMT054)"
          type: string
          default: "${header.MessageType}"
        source:
          title: "Source"
          description: "Source of the message (e.g., MQ, HTTP, KAFKA)"
          type: string
          default: "${header.Source}"
        payload:
          title: "Payload"
          description: "Message payload content"
          type: string
          default: "${body}"
        processingStatus:
          title: "Processing Status"
          description: "Processing status of the message"
          type: string
          default: "RECEIVED"
        dataSource:
          title: "Data Source"
          description: "Reference to the configured DataSource bean"
          type: string
          default: "#dataSource"
        tableName:
          title: "Table Name"
          description: "Database table name for persistence"
          type: string
          default: "pixel_v2.tb_messages"
        enableBatchProcessing:
          title: "Enable Batch Processing"
          description: "Enable batch processing for collections of messages"
          type: boolean
          default: true
    template:
      from:
        uri: "kamelet:source"
        steps:
          - log:
              message: "k-db-tx-messages: Starting message persistence - messageId=${header.MessageId}, correlationId=${header.CorrelationId}, type=${header.MessageType}, source=${header.Source}, bodySize=${body.length()}"
              loggingLevel: "INFO"

          # Store original body to restore it after database operation
          - setHeader:
              name: "OriginalBody"
              simple: "${body}"

          - setHeader:
              name: "PersistenceTimestamp"
              simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}"

          - setHeader:
              name: "SqlMessageId"
              simple: "${header.MessageId}"
              
          - setHeader:
              name: "SqlCorrelationId"
              simple: "${header.CorrelationId}"
              
          - setHeader:
              name: "SqlMessageType"
              simple: "${header.MessageType}"
              
          - setHeader:
              name: "SqlSource"
              simple: "${header.Source}"
              
          - setHeader:
              name: "SqlPayload"
              simple: "${header.OriginalBody}"
              
          - setHeader:
              name: "SqlProcessingStatus"
              constant: "RECEIVED"

          # Check if body is a collection and batch processing is enabled
          - choice:
              when:
                - simple: "${header.EnableBatchProcessing} == true && ${body} is 'java.util.Collection'"
                  steps:
                    - log:
                        message: "k-db-tx-messages: Processing batch of ${body.size()} messages"
                        loggingLevel: "INFO"
                    
                    # Use split to process each message in the collection
                    - split:
                        simple: "${body}"
                        parallelProcessing: false
                        streaming: false
                        steps:
                          - setHeader:
                              name: "MessageId"
                              simple: "MSG-${date:now:yyyyMMddHHmmssSSS}-${exchangeProperty.CamelSplitIndex}"
                          - setHeader:
                              name: "CorrelationId"
                              simple: "${header.CorrelationId}"
                          - setHeader:
                              name: "MessageType"
                              simple: "${header.MessageType}"
                          - setHeader:
                              name: "Source"
                              simple: "${header.Source}"
                          - setHeader:
                              name: "Payload"
                              simple: "${body}"
                          # Store current split body before database operation
                          - setHeader:
                              name: "OriginalBody"
                              simple: "${body}"
                          - doTry:
                              steps:
                                - setBody:
                                    simple: "INSERT INTO pixel_v2.tb_messages (message_id, correlation_id, message_type, source, payload, processing_status, received_at, created_at, updated_at) VALUES ('${header.MessageId}', '${header.CorrelationId}', '${header.MessageType}', '${header.Source}', '${header.OriginalBody}', 'RECEIVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
                                - to:
                                    uri: "jdbc:dataSource"
                                # Restore current batch item body
                                - setBody:
                                    simple: "${header.OriginalBody}"
                                - log:
                                    message: "k-db-tx-messages: Batch message persisted - Index: ${exchangeProperty.CamelSplitIndex}, ID: ${header.MessageId}"
                                    loggingLevel: "INFO"
                              doCatch:
                                - exception: ["java.lang.Exception"]
                                  steps:
                                    - log:
                                        message: "k-db-tx-messages: Batch message failed - Index: ${exchangeProperty.CamelSplitIndex}, Error: ${exception.message}"
                                        loggingLevel: "ERROR"
                                    - throwException:
                                        exceptionType: "java.lang.RuntimeException"
                                        message: "Batch message persistence failed: ${exception.message}"
                    # Restore original body after batch processing
                    - setBody:
                        simple: "${header.OriginalBody}"
                    - setHeader:
                        name: "PersistenceStatus"
                        constant: "BATCH_SUCCESS"
                    - setHeader:
                        name: "PersistenceOperation"
                        constant: "BATCH_INSERT"
                    - log:
                        message: "k-db-tx-messages: Batch processing completed successfully"
                        loggingLevel: "INFO"
                        
              otherwise:
                steps:
                  # Debug log to verify parameter values for single message
                  - log:
                      message: "k-db-tx-messages: About to execute SQL for single message - messageId=${header.MessageId}, correlationId=${header.CorrelationId}, messageType=${header.MessageType}, source=${header.Source}"
                      loggingLevel: "INFO"

                  # Execute database insert for single message with proper error handling  
                  - doTry:
                      steps:
                        - setBody:
                            simple: "INSERT INTO pixel_v2.tb_messages (message_id, correlation_id, message_type, source, payload, processing_status, received_at, created_at, updated_at) VALUES ('${header.SqlMessageId}', '${header.SqlCorrelationId}', '${header.SqlMessageType}', '${header.SqlSource}', '${header.SqlPayload}', 'RECEIVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
                        - to:
                            uri: "jdbc:dataSource"
                        
                        # Restore original body after database operation
                        - setBody:
                            simple: "${header.OriginalBody}"
                        
                        - setHeader:
                            name: "PersistenceStatus"
                            constant: "SUCCESS"
                            
                        - setHeader:
                            name: "PersistenceRecordId"
                            simple: "${header.SqlMessageId}"
                            
                        - setHeader:
                            name: "PersistenceOperation"
                            constant: "INSERT"
                            
                        - log:
                            message: "k-db-tx-messages: Single message persisted successfully - ID=${header.SqlMessageId}, Table=pixel_v2.tb_messages"
                            loggingLevel: "INFO"
                      doCatch:
                        - exception: ["java.lang.Exception"]
                          steps:
                            - setHeader:
                                name: "PersistenceStatus"
                                constant: "FAILED"
                                
                            - setHeader:
                                name: "PersistenceError"
                                simple: "${exception.message}"
                                
                            - setHeader:
                                name: "PersistenceOperation"
                                constant: "INSERT_FAILED"
                                
                            - log:
                                message: "k-db-tx-messages: ❌ Single message persistence failed - ID=${header.SqlMessageId}, Error=${exception.message}"
                                loggingLevel: "ERROR"
                                
                            # Re-throw exception so parent route can catch it and route to error handler
                            - throwException:
                                exceptionType: "java.lang.RuntimeException"
                                message: "Database persistence failed: ${exception.message}"

          - log:
              message: "k-db-tx-messages: Persistence completed - Status=${header.PersistenceStatus}, ID=${header.SqlMessageId}"
              loggingLevel: "DEBUG"