apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-log-flow-summary
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "K-Log Flow Summary"
    description: |-
      Creates and publishes flow summary logs to Kafka for PACS008 processing monitoring
    type: object
    properties:
      step:
        title: Processing Step
        description: Current processing step
        type: string
      kafkaTopicName:
        title: Kafka Topic Name
        description: Kafka topic for flow summary logs
        type: string
      brokers:
        title: Kafka Brokers
        description: Kafka broker endpoints
        type: string
  template:
    from:
      uri: "kamelet:source"
      steps:
        # Recalculate step based on failure count
        - choice:
            when:
              - simple: "${exchangeProperty.failureCount} > 0 && '{{step}}' == 'COMPLETED'"
                steps:
                  - setProperty:
                      name: "actualStep"
                      simple: "FAILURE"
            otherwise:
              steps:
                - setProperty:
                    name: "actualStep"
                    simple: "{{step}}"
        
        - setHeader:
            name: "LogMessage"
            simple: |
              {"flowOccurId":"${header.FlowOccurId}","flowCode":"${header.FlowCode}","flowStatusCode":"${exchangeProperty.actualStep}","flowCountryCode":"${header.FlowCountryCode}","flowCountryId":"${header.FlowCountryId}","flowTypeId":1,"flowComment":"${header.FlowCode} payment processing ${exchangeProperty.actualStep}","nbOutExpected":1,"nbOutCompleted":0,"nbError":0,"nbRemitance":0,"nbTransaction":1,"nbReplay":0,"issuingPartnerCode":"MQ_ACTIVEMQ","issuingPartnerLink":"tcp://pixel-v2-activemq:61616","recipientPartnerCode":"KAFKA_CLUSTER","recipientPartnerLink":"kafka:29092","lastLogId":"LOG-${date:now:yyyyMMddHHmmssSSS}","lastLogComponent":"processing-flow","lastLogDatetime":"${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}","lastLogStatusCode":"SUCCESS","lastUpdateDatetime":"${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}","lastUpdateUser":"system","inputFilePath":"inputFilePath","inputFileSize":"${bodyAs(String).length()}B","beginFlowDatetime":"${header.BeginFlowDateTime}","currentClientDatetime":"${date:now:yyyy-MM-dd'T'HH:mm:ss.SSS}","beginFlowDate":"${header.BeginFlowDate}","lastUpdateDate":"${date:now:yyyy-MM-dd}","region":"EU"}
        - setHeader:
            name: "KafkaKey"
            simple: "${header.FlowOccurId}"
        - setHeader:
            name: "originalBody"
            simple: "${body}"
        - setBody:
            simple: "${header.LogMessage}"
        - to:
            uri: "kafka:{{kafkaTopicName}}?brokers={{brokers}}&keySerializer=org.apache.kafka.common.serialization.StringSerializer&valueSerializer=org.apache.kafka.common.serialization.StringSerializer"
        - setBody:
            simple: "${header.originalBody}"
        - removeHeader:
            name: "originalBody"
        # Send to sink
        - to: "kamelet:sink"
