apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-log-flow-summary
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "K-Log Flow Summary"
    description: |-
      Creates and publishes flow summary logs to Kafka for PACS008 processing monitoring
    type: object
    properties:
      step:
        title: Processing Step
        description: Current processing step
        type: string
        default: "IN_PROGRESS"
      kafkaTopicName:
        title: Kafka Topic Name
        description: Kafka topic for flow summary logs
        type: string
        default: "flow-summary"
      brokers:
        title: Kafka Brokers
        description: Kafka broker endpoints
        type: string
        default: "pixel-v2-kafka:29092"
  template:
    from:
      uri: "kamelet:source"
      steps:
        - setHeader:
            name: "logMessage"
            simple: |
              {"flowOccurId":"${header.MessageId}","flowCode":"${header.flowCode}","flowStatusCode":"${header.step}","flowCountryCode":"${header.flowCountryCode}","flowCountryId":"${header.flowCountryId}","flowTypeId":1,"flowComment":"${header.flowCode} payment processing ${header.step}","nbOutExpected":1,"nbOutCompleted":0,"nbError":0,"nbRemitance":0,"nbTransaction":1,"nbReplay":0,"issuingPartnerCode":"MQ_ACTIVEMQ","issuingPartnerLink":"tcp://pixel-v2-activemq:61616","recipientPartnerCode":"KAFKA_CLUSTER","recipientPartnerLink":"kafka:29092","lastLogId":"LOG-${date:now:yyyyMMddHHmmssSSS}","lastLogComponent":"pacs008-processing-flow","lastLogDatetime":"${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}","lastLogStatusCode":"SUCCESS","lastUpdateDatetime":"${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}","lastUpdateUser":"system","inputFilePath":"pacs008.input.queue","inputFileSize":"${bodyAs(String).length()}B","beginFlowDatetime":"${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}","currentClientDatetime":"${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}","beginFlowDate":"${date:now:yyyy-MM-dd}","lastUpdateDate":"${date:now:yyyy-MM-dd}","region":"EU"}
        - setHeader:
            name: "kafka.KEY"
            simple: "${header.MessageId}"
        - setHeader:
            name: "originalBody"
            simple: "${body}"
        - setBody:
            simple: "${header.logMessage}"
        - removeHeader:
            name: "logMessage"
        - toD:
            uri: "kamelet:k-kafka-publisher?topic={{kafkaTopicName}}&brokers={{brokers}}&key=${header.kafka.KEY}"
        - setBody:
            simple: "${header.originalBody}"
        - removeHeader:
            name: "originalBody"
