apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-mq-message-receiver
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-MQ Message Receiver (Generic JMS)"
    description: "Consumes messages from JMS queues using connection parameters or external connection factory, logs receipt details, and routes messages for further processing"
    required: [queueName]
    properties:
      queueName:
        title: "Queue Name"
        type: string
        description: "Queue name to consume messages from"
      brokerUrl:
        title: "Broker URL"
        type: string
        description: "ActiveMQ broker URL (e.g., tcp://localhost:61616)"
        default: "tcp://localhost:61616"
      username:
        title: "Username"
        type: string
        description: "ActiveMQ username"
        default: "admin"
      password:
        title: "Password"
        type: string
        description: "ActiveMQ password"
        default: "admin"
      connectionFactory:
        title: "Connection Factory Reference"
        type: string
        description: "Reference to JMS connection factory bean (e.g., #jmsConnectionFactory). If not provided, will create one from brokerUrl/username/password"
        default: ""
      concurrentConsumers:
        title: "Concurrent Consumers"
        type: integer
        description: "Number of concurrent consumers for parallel message processing"
        default: 1
      autoStartup:
        title: "Auto Startup"
        type: boolean
        description: "Whether to auto-start the consumer"
        default: true
  template:
    beans:
      - name: activeMQConnectionFactory
        type: "#class:org.apache.activemq.ActiveMQConnectionFactory"
        properties:
          brokerURL: "{{brokerUrl}}"
          userName: "{{username}}"
          password: "{{password}}"
    from:
      uri: "jms:queue:{{queueName}}?connectionFactory=#activeMQConnectionFactory&concurrentConsumers={{concurrentConsumers}}&autoStartup={{autoStartup}}"
      steps:
        - log:
            message: "[K-MQ-MESSAGE-RECEIVER] Message received from queue: {{queueName}}, MessageId: ${header.JMSMessageID}, CorrelationId: ${header.JMSCorrelationID}"
        - log:
            message: "[K-MQ-MESSAGE-RECEIVER] DEBUG: Continuing kamelet processing..."
        - setHeader:
            name: "ReceivedTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSZ}"
        - setHeader:
            name: "SourceQueue"
            constant: "{{queueName}}"
        - setHeader:
            name: "flowCode"
            constant: "PACS008"
        - log:
            message: "[K-MQ-MESSAGE-RECEIVER] Headers: ${headers}"
        - log:
            message: "[K-MQ-MESSAGE-RECEIVER] Calling k-log-flow-summary with flowCode: ${header.flowCode}"
        - to:
            uri: "kamelet:k-log-flow-summary?step=IN_PROGRESS&kafkaTopicName=${header.flowCode}-flow-summary"