apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-mq-message-receiver
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-MQ Message Receiver (ActiveMQ Classic)"
    description: "Consumes messages from ActiveMQ Classic (JMS), logs receipt details, and routes messages for further processing"
    required: [destination, brokerUrl]
    properties:
      destination:
        title: "MQ destination (queue)"
        type: string
      brokerUrl:
        title: "Broker URL"
        type: string
        description: "ActiveMQ broker URL (e.g., tcp://localhost:61617)"
      user:
        title: "Broker username"
        type: string
        description: "Username for connecting to the broker"
        default: "admin"
      password:
        title: "Broker password"
        type: string
        description: "Password for connecting to the broker"
        default: "admin"
      concurrentConsumers:
        title: "Concurrent Consumers"
        type: integer
        description: "Number of concurrent consumers for parallel message processing"
        default: 1
  template:
    from:
      uri: "activemq:queue:{{destination}}"
      parameters:
        # ActiveMQ connection parameters
        brokerURL: "{{brokerUrl}}"
        userName: "{{user}}"
        password: "{{password}}"
        # Consumer configuration
        concurrentConsumers: "{{concurrentConsumers}}"
        # Connection settings
        trustAllPackages: true
        # Auto-start the consumer
        autoStartup: true