apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-mq-message-receiver
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-MQ Message Receiver (ActiveMQ Artemis)"
    description: "Consumes messages from ActiveMQ Artemis (JMS), logs receipt details, and routes messages for further processing"
    required: [destination]
    properties:
      destination:
        title: "MQ destination (queue)"
        type: string
      brokerUrl:
        title: "Broker URL"
        type: string
        description: "ActiveMQ Artemis broker URL (e.g., tcp://localhost:61616)"
      user:
        title: "Broker username"
        type: string
        description: "Username for connecting to the broker"
      password:
        title: "Broker password"
        type: string
        description: "Password for connecting to the broker"
      jmsConnectionFactoryRef:
        title: "JMS Connection Factory Bean name"
        type: string
        default: "artemisConnectionFactory"
      acknowledgmentModeName:
        title: "JMS Acknowledgment Mode"
        type: string
        description: "JMS acknowledgment mode (AUTO_ACKNOWLEDGE, CLIENT_ACKNOWLEDGE, DUPS_OK_ACKNOWLEDGE)"
        default: "AUTO_ACKNOWLEDGE"
      transacted:
        title: "Enable JMS Transactions"
        type: boolean
        description: "Enable JMS local transactions for transactional message processing"
        default: false
  template:
    from:
      uri: "jms:queue:{{destination}}"
      parameters:
        # Use ActiveMQ Artemis ConnectionFactory
        connectionFactory: "#{{jmsConnectionFactoryRef}}"
        # Configurable acknowledgment mode for transactional processing
        acknowledgementModeName: "{{acknowledgmentModeName}}"
        # Concurrent consumers for high throughput
        concurrentConsumers: 5
        # Maximum concurrent consumers
        maxConcurrentConsumers: 10
        # Auto-start the consumer
        autoStartup: true
        # Configurable local transactions
        transacted: "{{transacted}}"
        # Enable message caching for improved performance
        cacheLevelName: "CACHE_CONSUMER"