apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-db-tx
  labels:
    camel.apache.org/kamelet.type: "sink"
    pixel.v2/category: "persistence"
    pixel.v2/version: "1.0.0"
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "4.1.0"
    camel.apache.org/provider: "Pixel V2"
    pixel.v2/description: "Persists payment messages and CDM objects to database via JPA transactions"
spec:
    definition:
      title: "Database Transaction"
      description: |
        Persists payment messages and CDM objects to database using JPA transactions.
        Works with plain JPA (no Spring required) for JBang compatibility.
        Supports dual entity types (MESSAGE/CDM) with transaction management and error handling.
      required: []
      properties:
        persistenceUnitName:
          title: "Persistence Unit Name"
          description: "JPA persistence unit name for database operations"
          type: string
          default: "pixelPersistenceUnit"
        enableAuditTrail:
          title: "Enable Audit Trail"
          description: "Whether to create audit trail entries for persisted messages"
          type: boolean
          default: true
        entityType:
          title: "Entity Type"
          description: "Type of entity to persist - MESSAGE for ReceivedMessage, CDM for CdmMessage"
          type: string
          default: "MESSAGE"
          enum: ["MESSAGE", "CDM"]
        persistenceOperation:
          title: "Persistence Operation"
          description: "Operation type - CREATE for new records, UPDATE for existing records"
          type: string
          default: "CREATE"
          enum: ["CREATE", "UPDATE"]
        batchSize:
          title: "Batch Size"
          description: "Number of messages to batch for persistence operations"
          type: integer
          default: 1
        timeoutSeconds:
          title: "Persistence Timeout"
          description: "Timeout in seconds for database operations"
          type: integer
          default: 30
    template:
      beans:
        - name: "jpaPersistenceProcessor"
          type: "com.pixel.v2.persistence.processor.JpaPersistenceProcessor"
      from:
        uri: "kamelet:source"
        steps:
          - log:
              message: "Starting JPA message persistence: messageId=${header.messageId}, type=${header.messageType}"
              loggingLevel: "DEBUG"

          - setHeader:
              name: "persistenceTimestamp"
              simple: "${date:now:yyyy-MM-dd HH:mm:ss.SSS}"

          - setHeader:
              name: "persistenceAction"
              constant: "SAVE_MESSAGE"

          - setHeader:
              name: "EntityType"
              simple: "{{entityType}}"

          - setHeader:
              name: "PersistenceOperation"
              simple: "{{persistenceOperation}}"

          - choice:
              when:
                - simple: "${body} == null || ${body} == ''"
                  steps:
                    - log:
                        message: "Empty message body detected for messageId=${header.messageId}"
                        loggingLevel: "WARN"
                    - setHeader:
                        name: "persistenceStatus"
                        constant: "ERROR"
                    - setHeader:
                        name: "persistenceError"
                        constant: "Empty message body"
                    - stop: {}

          - log:
              message: "Processing message with JPA persistence processor for messageId=${header.messageId}"
              loggingLevel: "DEBUG"
              
          - to: "bean:jpaPersistenceProcessor?method=process"

          - choice:
              when:
                - simple: "${header.persistenceStatus} == 'SUCCESS'"
                  steps:
                    - log:
                        message: "Message persisted successfully: id=${header.persistedMessageId}, messageId=${header.messageId}"
                        loggingLevel: "INFO"
                    - setBody:
                        simple: |
                          {
                            "status": "SUCCESS",
                            "messageId": "${header.messageId}",
                            "persistedId": "${header.persistedMessageId}",
                            "entityType": "${header.EntityType}",
                            "timestamp": "${header.persistenceTimestamp}"
                          }

              otherwise:
                steps:
                  - log:
                      message: "Message persistence failed: messageId=${header.messageId}, error=${header.persistenceError}"
                      loggingLevel: "ERROR"
                  - setBody:
                      simple: |
                        {
                          "status": "ERROR",
                          "messageId": "${header.messageId}",
                          "error": "${header.persistenceError}",
                          "timestamp": "${header.persistenceTimestamp}"
                        }

          - log:
              message: "JPA message persistence completed: messageId=${header.messageId}, status=${header.persistenceStatus}"
              loggingLevel: "INFO"