apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: payment-ingestion-routes
spec:
  flows:
    # Main Payment Ingestion Orchestrator Route
    - route:
        id: payment-ingestion-orchestrator
        from:
          uri: "timer:trigger"
          parameters:
            period: 30000
            repeatCount: 1
        steps:
          - log:
              message: "Starting Payment Ingestion Process"
          - to:
              uri: "direct:mq-receipt"
          - to:
              uri: "direct:api-receipt"
          - to:
              uri: "direct:file-receipt"
          - log:
              message: "Payment Ingestion Process Completed"

    # Reference Data Enrichment Route
    - route:
        id: reference-enrichment
        from:
          uri: "direct:reference-enrichment"
        steps:
          - log:
              message: "Enriching payment with reference data"
          - setHeader:
              name: "enriched"
              constant: "true"
          - log:
              message: "Reference data enrichment completed"

    # Validation Step Route
    - route:
        id: validation-step
        from:
          uri: "direct:validation-step"
        steps:
          - log:
              message: "Validating payment message"
          - choice:
              when:
                - predicate:
                    simple: "${body} != null"
                  steps:
                    - log:
                        message: "Payment validation passed"
              otherwise:
                steps:
                  - log:
                      message: "Payment validation failed"
                  - throwException:
                      exceptionType: "java.lang.IllegalArgumentException"
                      message: "Invalid payment message"

    # Idempotence Check Route
    - route:
        id: idempotence-check
        from:
          uri: "direct:idempotence-check"
        steps:
          - log:
              message: "Checking payment idempotence"
          - setHeader:
              name: "idempotence-key"
              simple: "${body.paymentId}"
          - log:
              message: "Idempotence check completed"

    # Kafka Publisher Route
    - route:
        id: kafka-publisher
        from:
          uri: "direct:kafka-publisher"
        steps:
          - log:
              message: "Publishing payment to Kafka"
          - setHeader:
              name: "kafka.TOPIC"
              constant: "payment-events"
          - to:
              uri: "kafka:payment-events"
              parameters:
                brokers: "localhost:9092"
          - log:
              message: "Payment published to Kafka successfully"

    # API Receipt Route
    - route:
        id: api-receipt-route
        from:
          uri: "direct:api-receipt"
        steps:
          - log:
              message: "Processing API receipt"
          - to:
              uri: "direct:reference-enrichment"
          - to:
              uri: "direct:validation-step"
          - to:
              uri: "direct:idempotence-check"
          - to:
              uri: "direct:kafka-publisher"