apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-batch-aggregation
  labels:
    camel.apache.org/kamelet.type: "action"
    pixel.v2/category: "aggregation"
    pixel.v2/version: "1.0.0"
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "4.1.0"
    camel.apache.org/provider: "Pixel V2"
    pixel.v2/description: "Aggregates messages into batches using configurable size and timeout parameters"
spec:
  definition:
    title: "Batch Aggregation"
    description: |
      Aggregates incoming messages into batches using size-based and time-based completion criteria.
      Uses MessageBatchAggregationStrategy to collect messages into a list for efficient batch processing.
      Supports configurable batch sizes and timeout intervals for different message types.
    required:
      - batchSize
      - timeoutMs
      - correlationKey
    properties:
      batchSize:
        title: "Batch Size"
        description: "Maximum number of messages to aggregate into a single batch"
        type: integer
        default: 1000
        example: 1000
      timeoutMs:
        title: "Timeout (milliseconds)"
        description: "Maximum time to wait for batch completion in milliseconds"
        type: integer
        default: 5000
        example: 5000
      correlationKey:
        title: "Correlation Key"
        description: "Key used to correlate messages for aggregation (messages with same key are batched together)"
        type: string
        default: "DEFAULT_BATCH_KEY"
        example: "PACS008_BATCH_KEY"
      messageType:
        title: "Message Type"
        description: "Type of messages being aggregated for logging purposes"
        type: string
        default: "MESSAGE"
        example: "PACS.008"
  template:
    from:
      uri: "kamelet:source"
      steps:
        - log:
            message: "[BATCH-AGG] Starting batch aggregation for {{messageType}} message: messageId=${header.JMSMessageID}"
            loggingLevel: "DEBUG"
        
        # Set batch metadata headers
        - setHeader:
            name: "BatchMessageType"
            constant: "{{messageType}}"
        - setHeader:
            name: "BatchCorrelationKey"
            constant: "{{correlationKey}}"
        - setHeader:
            name: "BatchMaxSize"
            constant: "{{batchSize}}"
        - setHeader:
            name: "BatchTimeoutMs"
            constant: "{{timeoutMs}}"
        
        # Message aggregation using MessageBatchAggregationStrategy
        - aggregate:
            correlationExpression:
              constant: "{{correlationKey}}"
            completionSize: "{{batchSize}}"
            completionTimeout: "{{timeoutMs}}"
            aggregationStrategy: "#messageBatchAggregationStrategy"
            steps:
              - log:
                  message: "[BATCH-AGG] Batch ready for processing: ${header.CamelAggregatedSize} {{messageType}} messages"
                  loggingLevel: "INFO"
              
              # Set final batch headers
              - setHeader:
                  name: "BatchCompleted"
                  constant: "true"
              - setHeader:
                  name: "BatchCompletionReason"
                  simple: "${header.CamelAggregatedCompletedBy}"
              - setHeader:
                  name: "BatchProcessingTimestamp"
                  simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSZ}"