apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-referentiel-data-loader
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "K-Referentiel Data Loader"
    description: "Loads configuration from external REST service and adds metadata to message headers for enrichment processing."
    required: [serviceUrl, flowId]
    properties:
      serviceUrl:
        title: "Service URL"
        description: "The HTTP endpoint used to retrieve configuration metadata."
        type: string
        default: "http://localhost:8099"
      flowId:
        title: "Flow ID"
        description: "The flow identifier to retrieve specific configuration (e.g., pacs008, pacs009, pain001, camt053)"
        type: string
        example: "pacs008"
      configEndpoint:
        title: "Configuration Endpoint Path"
        description: "Path to append to serviceUrl for configuration retrieval (e.g., /api/config)"
        type: string
        default: "/api/config"
  template:
    from:
      uri: "kamelet:source"
      steps:
        - log: "Loading configuration metadata for message processing"
        - set-header:
            name: "OriginalBody"
            simple: "${body}"
        - set-header:
            name: "CamelHttpMethod"
            constant: "GET"
        - to: "{{serviceUrl}}{{configEndpoint}}/{{flowId}}?throwExceptionOnFailure=false"
        - choice:
            when:
              - simple: "${body} != null && ${body} != ''"
                steps:
                  - log: "Configuration retrieved successfully: ${body}"
                  - set-header:
                      name: "CmdMapping"
                      jsonpath: "$.cmdMapping"
                  - set-header:
                      name: "Rail"
                      jsonpath: "$.rail"
                  - set-header:
                      name: "Mode"
                      jsonpath: "$.mode"
                  - set-header:
                      name: "NeedSplit"
                      jsonpath: "$.needSplit"
                  - set-header:
                      name: "SplitExpr"
                      jsonpath: "$.splitExpr"
                  - set-header:
                      name: "ChunkSize"
                      jsonpath: "$.chunkSize"
                  - set-header:
                      name: "Outputs"
                      jsonpath: "$.outputs"
                  - set-header:
                      name: "XsltFileToCdm"
                      jsonpath: "$.xsltFileToCdm"
                  - set-header:
                      name: "XsltFileFromCdm"
                      jsonpath: "$.xsltFileFromCdm"
                  - set-header:
                      name: "XsdFlowFile"
                      jsonpath: "$.xsdFlowFile"
                  - set-header:
                      name: "XsdCdmFile"
                      jsonpath: "$.xsdCdmFile"
                  - set-header:
                      name: "KafkaBroker"
                      jsonpath: "$.kafkaBroker"
                  - set-header:
                      name: "KafkaTopic"
                      jsonpath: "$.kafkaTopic"
                  - log: "Configuration headers set - CmdMapping: ${header.CmdMapping}, Rail: ${header.Rail}, Mode: ${header.Mode}, FlowId: {{flowId}}"
            otherwise:
              steps:
                - log: "Failed to retrieve configuration, using defaults"
                - set-header:
                    name: "CmdMapping"
                    constant: "default_mapping"
                - set-header:
                    name: "Rail"
                    constant: "standard"
                - set-header:
                    name: "Mode"
                    constant: "normal"
                - set-header:
                    name: "NeedSplit"
                    constant: "false"
                - set-header:
                    name: "SplitExpr"
                    constant: ""
                - set-header:
                    name: "ChunkSize"
                    constant: "1000"
                - set-header:
                    name: "Outputs"
                    constant: "[]"
                - set-header:
                    name: "XsltFileToCdm"
                    constant: "xslt/default-to-cdm.xslt"
                - set-header:
                    name: "XsltFileFromCdm"
                    constant: "xslt/cdm-to-default.xslt"
                - set-header:
                    name: "XsdFlowFile"
                    constant: "xsd/default.xsd"
                - set-header:
                    name: "XsdCdmFile"
                    constant: "xsd/cdm.xsd"
                - set-header:
                    name: "KafkaBroker"
                    constant: "localhost:9092"
                - set-header:
                    name: "KafkaTopic"
                    constant: "default-topic"
        - set-body:
            simple: "${header.OriginalBody}"
        - remove-header:
            name: "OriginalBody"
        - log: "Message enriched with configuration headers including transformation and Kafka settings, original payload preserved"
        - to: "kamelet:sink"
