apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-duplicate-check
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "K-Duplicate Check"
    description: |-
      Performs duplicate check processing with file size validation and database operations
    type: object
    properties:
      dataSource:
        title: "Data Source"
        description: "JDBC data source name"
        type: string
      disableCheckDB:
        title: "Disable DB Check"
        description: "Global flag to disable duplicate check"
        type: boolean
        default: false
      disableCheckMaxFileSize:
        title: "Disable Max File Size Check" 
        description: "Flag to disable maximum file size check"
        type: boolean
        default: false
      maxFileSize:
        title: "Max File Size"
        description: "Maximum allowed file size in bytes"
        type: integer
        default: 10485760
  template:
    from:
      uri: "kamelet:source"
      steps:
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}"
        - setHeader:
            name: "ContextId"
            constant: "duplicate-check-${uuid}"
        - toD:
            uri: "kamelet:k-log-events?kafkaTopicName=${headers.KafkaLogTopicName}&brokers=${headers.Brokers}&flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&logMessageTxt=Start DuplicateCheck - flowOccurId: ${header.FlowOccurId}, FlowCode: ${header.FlowCode}&level=INFO&processingTimestamp=${header.ProcessingTimestamp}&contextId=${header.ContextId}&component=K-DUPLICATE-CHECK"
            pattern: "InOnly"
        # 1. Check if global DB check is disabled
        - choice:
            when:
              - simple: "{{disableCheckDB}} == true"
                steps:
                  - log:
                      message: "DuplicateCheck is disabled. Occ_Id: ${header.flowOccurId}"
                      loggingLevel: INFO
            otherwise:
              steps:
                # 2. Save original body before any processing
                - setHeader:
                    name: "OriginalBody"
                    simple: "${body}"
                
                # 3. Extract flowId from RefFlowData JSON
                - setBody:
                    simple: "${header.RefFlowData}"
                # Log the RefFlowData content for debugging
                - log:
                    message: "RefFlowData content: ${body}"
                    loggingLevel: DEBUG
                - doTry:
                    steps:
                      - setHeader:
                          name: "FlowId"
                          jsonpath: "$.flow.FlowID"
                      - setHeader:
                          name: "PartnerId"
                          jsonpath: "$.partnerIn.partnerCode"
                    doCatch:
                      - exception: "com.jayway.jsonpath.PathNotFoundException"
                        steps:
                          - log:
                              message: "JSONPath error - RefFlowData structure may be incorrect: ${exception.message}"
                              loggingLevel: ERROR
                          - setHeader:
                              name: "FlowId"
                              simple: "UNKNOWN"
                          - setHeader:
                              name: "PartnerId"
                              simple: "UNKNOWN"
                
                # 4. Restore original body immediately
                - setBody:
                    simple: "${header.OriginalBody}"

                # 5. Log that duplicate check is enabled
                - log:
                    message: "DuplicateCheck is enabled. Occ_Id: ${header.flowOccurId}, FlowId: ${header.FlowId} , PartnerId: ${header.PartnerId}"
                    loggingLevel: INFO

                # 6. Compute checksum and file size using Java processor
                - process:
                    ref: "duplicateCheckProcessor"

                # 5. File size check
                - choice:
                    when:
                      - simple: "{{disableCheckMaxFileSize}} == false"
                        steps:
                          - choice:
                              when:
                                - simple: "${exchangeProperty.fileSize} > {{maxFileSize}}"
                                  steps:
                                    - log:
                                        message: "TEC00064: Max file size exceeded. File size: ${exchangeProperty.fileSize} bytes, Max allowed: {{maxFileSize}} bytes"
                                        loggingLevel: ERROR
                                    - setHeader:
                                        name: "DuplicateCheckError"
                                        simple: "TEC00064"

                # 6. Database duplicate check (only if no file size error)
                - choice:
                    when:
                      - simple: "${header.DuplicateCheckError} == null"
                        steps:
                          - log:
                              message: "Performing duplicate check for flowId: ${header.flowId}, checksum: ${exchangeProperty.checksum} , PartnerId: ${header.PartnerId}"
                              loggingLevel: INFO
                          
                          # 6.1 Check for existing duplicates first
                          - to:
                              uri: "sql:SELECT COUNT(*) as count FROM pixel_v2.TECH_DUPLICATE_CHECK WHERE FLOWID = :#${header.FlowId} AND CHECKSUM = :#${exchangeProperty.checksum}?dataSource={{dataSource}}"
                          
                          - choice:
                              when:
                                - simple: "${body[0]['count']} > 0"
                                  steps:
                                    - log:
                                        message: "DCH00001: Duplicate flow detected for flowId: ${header.FlowId}"
                                        loggingLevel: ERROR
                                    - setHeader:
                                        name: "DuplicateCheckError"
                                        simple: "DCH00001"
                                    - throwException:
                                        exceptionType: "java.lang.IllegalStateException"
                                        message: "DCH00001: Duplicate flow detected for flowId: ${header.FlowId}, checksum: ${exchangeProperty.checksum}"
                              otherwise:
                                steps:
                                  # 6.2 Insert new record
                                  - to:
                                      uri: "sql:INSERT INTO pixel_v2.TECH_DUPLICATE_CHECK (FLOWOCCUR_ID, PARTNER_ID, CHECKSUM, FLOWID, RECEIPT_DTE) VALUES (:#${header.flowOccurId}, :#${header.PartnerId}, :#${exchangeProperty.checksum}, :#${header.FlowId}, CURRENT_TIMESTAMP)?dataSource={{dataSource}}"
                                  
                                  # 7. Success
                                  - log:
                                      message: "DuplicateCheck successfully completed. Occ_Id: ${header.FlowOccurId}"
                                      loggingLevel: INFO

        # Restore original body before continuing
        - setBody:
            simple: "${header.OriginalBody}"
        - removeProperty:
            name: "OriginalBody"
        # Log completion of DuplicateCheck
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}"
        - toD:
            uri: "kamelet:k-log-events?kafkaTopicName=${headers.KafkaLogTopicName}&brokers=${headers.Brokers}&flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&logMessageTxt=Start DuplicateCheck - flowOccurId: ${header.FlowOccurId}, FlowCode: ${header.FlowCode}&level=INFO&processingTimestamp=${header.ProcessingTimestamp}&contextId=${header.ContextId}&component=K-DUPLICATE-CHECK"
            pattern: "InOnly"
        
        # Continue to next step
        - to: "kamelet:sink"