apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-techpivot-enrichment
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "1.0.1-SNAPSHOT"
    camel.apache.org/provider: "PIXEL-V2"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "PIXEL-V2 Technical Pivot Enrichment Kamelet"
    description: |-
      Technical pivot data enrichment kamelet for payment processing.
      Takes map properties and builds a complete TechnicalPivot.json structure.
      Used to create structured technical pivot data from flow properties.
    required:
      - flowId
      - flowCode
      - flowName
    type: object
    properties:
      flowId:
        title: Flow ID
        description: Unique identifier for the flow
        type: integer
        example: 1
      flowCode:
        title: Flow Code
        description: The flow code identifier
        type: string
        example: "ICHSIC"
      flowName:
        title: Flow Name
        description: Human-readable flow name
        type: string
        example: "ICHSIC Payment Flow"
      flowTypeName:
        title: Flow Type Name
        description: Type of the flow
        type: string
        default: "Payment Processing"
      flowDirection:
        title: Flow Direction
        description: Direction of the flow (IN, OUT, BID)
        type: string
        default: "BID"
      flowEnabled:
        title: Flow Enabled
        description: Whether the flow is enabled
        type: string
        default: "Y"
      fileName:
        title: File Name
        description: Name of the file being processed
        type: string
        default: ""
      fileContent:
        title: File Content
        description: Content of the file being processed
        type: string
        default: ""
      inputPartner:
        title: Input Partner
        description: Input partner information (JSON string)
        type: string
        default: "{}"
      outputPartners:
        title: Output Partners
        description: Array of output partners (JSON string)
        type: string
        default: "[]"
      countries:
        title: Countries
        description: Comma-separated list of countries
        type: string
        default: ""
      functionalProperties:
        title: Functional Properties
        description: Functional properties as JSON string (array of Key/Value objects)
        type: string
        default: "[]"
  dependencies:
    - "camel:kamelet"
    - "camel:jackson" 
    - "camel:log"
    - "camel:groovy"
    - "camel:spring-boot-starter"
  template:
    from:
      uri: "kamelet:source"
      steps:
        # Store original message body
        - setHeader:
            name: "OriginalMessageBody"
            simple: "${body}"
        
        # Log start of technical pivot enrichment
        - log: 
            message: "Building TechnicalPivot for flow ${header.flowCode} (ID: ${header.flowId})"
            loggingLevel: INFO
            
        # Build the TechnicalPivot JSON structure
        - script:
            groovy: |
              import groovy.json.JsonBuilder
              import groovy.json.JsonSlurper
              
              def jsonSlurper = new JsonSlurper()
              
              // Parse input parameters
              def inputPartner = [:]
              try {
                inputPartner = jsonSlurper.parseText('{{inputPartner}}' ?: '{}')
              } catch (Exception e) {
                inputPartner = [:]
              }
              
              def outputPartners = []
              try {
                outputPartners = jsonSlurper.parseText('{{outputPartners}}' ?: '[]')
              } catch (Exception e) {
                outputPartners = []
              }
              
              def functionalProperties = []
              try {
                functionalProperties = jsonSlurper.parseText('{{functionalProperties}}' ?: '[]')
              } catch (Exception e) {
                functionalProperties = []
              }
              
              // Parse countries
              def countriesList = []
              if ('{{countries}}' && '{{countries}}'.trim()) {
                countriesList = '{{countries}}'.split(',').collect { it.trim() }
              }
              
              // Build the TechnicalPivot structure
              def techPivot = [
                TechPivotRoot: [
                  FileName: '{{fileName}}',
                  FileContent: '{{fileContent}}',
                  Flow: [
                    FlowID: {{flowId}},
                    FlowCode: '{{flowCode}}',
                    FlowName: '{{flowName}}',
                    FlowTypeName: '{{flowTypeName}}',
                    FlowDirection: '{{flowDirection}}',
                    FlowEnabled: '{{flowEnabled}}',
                    FlowFuncPrty: functionalProperties,
                    Countries: [
                      Country: countriesList
                    ]
                  ],
                  Input: inputPartner,
                  Output: outputPartners,
                  Properties: [:],
                  Generic: [:]
                ]
              ]
              
              // Convert to JSON string
              def jsonBuilder = new JsonBuilder(techPivot)
              def techPivotJson = jsonBuilder.toPrettyString()
              
              // Set the result as message body
              exchange.in.body = techPivotJson
              exchange.in.headers['TechnicalPivotJson'] = techPivotJson
              exchange.in.headers['ContentType'] = 'application/json'
        
        # Log completion
        - log: 
            message: "TechnicalPivot JSON structure created successfully for flow {{flowCode}}"
            loggingLevel: INFO
            
        # Send to sink
        - to: "kamelet:sink"