apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-xsd-validation
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "K-XSD Validation"
    description: "Validates XML messages (single or collection) against XSD schemas stored in the kamelet's resource folder. Supports both single String messages and Collection<String> for batch validation."
    required: [xsdFileName]
    properties:
      xsdFileName:
        title: "XSD File Name"
        type: string
        description: "Name of the XSD schema file to use for validation (file must exist in /xsd folder)"
        example: "pacs.008.001.08.xsd"
      validationMode:
        title: "Validation Mode"
        type: string
        description: "Validation mode: STRICT (stop on error) or LENIENT (log warnings but continue)"
        default: "STRICT"
        enum: ["STRICT", "LENIENT"]
      enableDetailedErrors:
        title: "Enable Detailed Error Messages"
        type: boolean
        description: "Include detailed XSD validation error messages in exceptions"
        default: true
      namespaceAware:
        title: "Namespace Aware Validation"
        type: boolean
        description: "Enable namespace-aware XML parsing and validation"
        default: true
  template:
    from:
      uri: "kamelet:source"
      steps:
        
        # Set validation headers
            
        - setHeader:
            name: "XsdFileName"
            simple: "{{xsdFileName}}"
            
        - setHeader:
            name: "ValidationMode"
            simple: "{{validationMode}}"
        
        # Log event before XSD validation
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyyMMddHHmmssSSS}"
        - setHeader:
            name: "ContextId"
            simple: "xsd-validation-${uuid}"
        - toD:
            uri: "kamelet:k-log-events?kafkaTopicName=${headers.KafkaLogTopicName}&brokers=${headers.Brokers}&flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&logMessageTxt=Start validation - flowOccurId: ${header.FlowOccurId}, XSD: {{xsdFileName}}&level=INFO&processingTimestamp=${header.ProcessingTimestamp}&contextId=${header.ContextId}&component=K-XSD-VALIDATION"
            pattern: "InOnly"
            
        # Validate XML against XSD using custom processor
        # Supports both single String messages and Collection<String> for batch validation
        - to:
            uri: "class:com.pixel.v2.validation.processor.XsdValidationProcessor"
        # Log event after XSD validation
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyyMMddHHmmssSSS}"
        - toD:
            uri: "kamelet:k-log-events?kafkaTopicName=${headers.kafkaTopicName}&brokers=${headers.kafkaBrokers}&flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&logMessageTxt=End validation - flowOccurId: ${header.FlowOccurId}, XSD: {{xsdFileName}}&level=INFO&processingTimestamp=${header.ProcessingTimestamp}&contextId=${header.ContextId}&component=K-XSD-VALIDATION"
            pattern: "InOnly"
            
        # Log validation success
        # - log:
        #     message: "[XSD-VALIDATION] ✅ Validation successful - XSD: {{xsdFileName}}, Scope: ${header.ValidationScope}, Count: ${header.ValidationCount}, Duration: ${header.ValidationDuration}ms"
        #     loggingLevel: INFO
                      
            
        # Continue to next step (validation passed)
        - to: "kamelet:sink"