# Distribution Message Processing Routes
# This file defines the main distribution message processing flows

- beans:
  - name: "distributionMessageProcessor"
    type: "com.pixel.v2.distribution.processor.DistributionMessageProcessor"

- route:
    id: "distribution-direct-input"
    description: "Handles messages received from direct endpoints"
    from:
      uri: "direct:distribution-input"
      steps:
        - log:
            message: "[DISTRIBUTION-DIRECT] Received message from direct endpoint: ${body}"
            loggingLevel: INFO
            
        - setHeader:
            name: "messageSource"
            constant: "DIRECT_ENDPOINT"
            
        - setHeader:
            name: "receiptTimestamp" 
            simple: "${date:now:yyyy-MM-dd HH:mm:ss.SSS}"
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_RECEIVED"
            
        # Log the message using k-log-tx kamelet
        - to:
            uri: "kamelet:k-log-tx"
            parameters:
              logLevel: "INFO"
              logSource: "distribution-service"
              logCategory: "ROUTE"
              correlationId: "${exchangeId}"
              
        - log:
            message: "[DISTRIBUTION-DIRECT] Message logged, routing for processing"
            
        - to:
            uri: "direct:distribution-process-message"

- route:
    id: "distribution-kafka-input"
    description: "Handles messages received from Kafka topics using k-kafka-message-receiver"
    from:
      uri: "kamelet:k-kafka-message-receiver"
      parameters:
        bootstrapServers: "{{distribution.kafka.bootstrap-servers}}"
        topic: "{{distribution.kafka.topics.input}}"
        groupId: "{{distribution.kafka.group-id}}"
        offsetReset: "{{distribution.kafka.auto-offset-reset}}"
        routingEndpoint: "direct:distribution-kafka-received"
      steps:
        - log:
            message: "[DISTRIBUTION-KAFKA] Received message from Kafka via k-kafka-message-receiver"

- route:
    id: "distribution-kafka-received"
    description: "Processes messages received from Kafka"
    from:
      uri: "direct:distribution-kafka-received"
      steps:
        - log:
            message: "[DISTRIBUTION-KAFKA] Processing Kafka message: Topic=${header.kafkaTopic}, Partition=${header.kafkaPartition}, Offset=${header.kafkaOffset}"
            loggingLevel: INFO
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_KAFKA_RECEIVED"
            
        # Log the Kafka message using k-log-tx kamelet
        - to:
            uri: "kamelet:k-log-tx"
            parameters:
              logLevel: "INFO"
              logSource: "distribution-service"
              logCategory: "ROUTE"
              correlationId: "${header.kafkaKey}"
              
        - log:
            message: "[DISTRIBUTION-KAFKA] Kafka message logged, routing for processing"
            
        - to:
            uri: "direct:distribution-process-message"

- route:
    id: "distribution-message-processor"
    description: "Main message processing logic"
    from:
      uri: "direct:distribution-process-message"
      steps:
        - log:
            message: "[DISTRIBUTION-PROCESSOR] Processing message from ${header.messageSource}"
            loggingLevel: INFO
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_PROCESSING"
            
        # Process the message using custom processor
        - bean:
            ref: "distributionMessageProcessor"
            
        - choice:
            when:
              - simple: "${header.processingResult} == 'SUCCESS'"
                steps:
                  - log:
                      message: "[DISTRIBUTION-PROCESSOR] Message processed successfully"
                      
                  - setHeader:
                      name: "processingStage"
                      constant: "DISTRIBUTION_SUCCESS"
                      
                  # Log success using k-log-tx
                  - to:
                      uri: "kamelet:k-log-tx"
                      parameters:
                        logLevel: "INFO"
                        logSource: "distribution-service"
                        logCategory: "BUSINESS"
                        correlationId: "${exchangeId}"
                        
                  - to:
                      uri: "direct:distribution-route-message"
            otherwise:
              steps:
                - log:
                    message: "[DISTRIBUTION-PROCESSOR] Message processing failed: ${header.processingError}"
                    loggingLevel: ERROR
                    
                - setHeader:
                    name: "processingStage"
                    constant: "DISTRIBUTION_ERROR"
                    
                # Log error using k-log-tx
                - to:
                    uri: "kamelet:k-log-tx"
                    parameters:
                      logLevel: "ERROR"
                      logSource: "distribution-service"
                      logCategory: "ERROR"
                      correlationId: "${exchangeId}"
                      
                - to:
                    uri: "direct:distribution-error-handler"

- route:
    id: "distribution-message-router"
    description: "Routes processed messages to appropriate destinations"
    from:
      uri: "direct:distribution-route-message"
      steps:
        - log:
            message: "[DISTRIBUTION-ROUTER] Routing message based on type: ${header.messageType}"
            loggingLevel: INFO
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_ROUTING"
            
        - choice:
            when:
              - simple: "${header.messageType} == 'PAYMENT'"
                steps:
                  - log:
                      message: "[DISTRIBUTION-ROUTER] Routing payment message"
                  - to:
                      uri: "direct:distribution-payment-handler"
              - simple: "${header.messageType} == 'TRANSACTION'"
                steps:
                  - log:
                      message: "[DISTRIBUTION-ROUTER] Routing transaction message"
                  - to:
                      uri: "direct:distribution-transaction-handler"
              - simple: "${header.messageType} == 'NOTIFICATION'"
                steps:
                  - log:
                      message: "[DISTRIBUTION-ROUTER] Routing notification message"
                  - to:
                      uri: "direct:distribution-notification-handler"
            otherwise:
              steps:
                - log:
                    message: "[DISTRIBUTION-ROUTER] Unknown message type, routing to default handler"
                - to:
                    uri: "direct:distribution-default-handler"

- route:
    id: "distribution-payment-handler"
    description: "Handles payment messages"
    from:
      uri: "direct:distribution-payment-handler"
      steps:
        - log:
            message: "[PAYMENT-HANDLER] Processing payment message: ${header.paymentId}"
            loggingLevel: INFO
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_PAYMENT_PROCESSING"
            
        # Log payment processing
        - to:
            uri: "kamelet:k-log-tx"
            parameters:
              logLevel: "INFO"
              logSource: "distribution-service"
              logCategory: "BUSINESS"
              correlationId: "${header.paymentId}"
              
        # Add payment-specific processing logic here
        - log:
            message: "[PAYMENT-HANDLER] Payment message processed and sent"
            
        - to:
            uri: "{{distribution.direct.output-endpoint}}"

- route:
    id: "distribution-transaction-handler"
    description: "Handles transaction messages"
    from:
      uri: "direct:distribution-transaction-handler"
      steps:
        - log:
            message: "[TRANSACTION-HANDLER] Processing transaction message: ${header.transactionId}"
            loggingLevel: INFO
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_TRANSACTION_PROCESSING"
            
        # Log transaction processing
        - to:
            uri: "kamelet:k-log-tx"
            parameters:
              logLevel: "INFO"
              logSource: "distribution-service"
              logCategory: "BUSINESS"
              correlationId: "${header.transactionId}"
              
        # Add transaction-specific processing logic here
        - log:
            message: "[TRANSACTION-HANDLER] Transaction message processed and sent"
            
        - to:
            uri: "{{distribution.direct.output-endpoint}}"

- route:
    id: "distribution-notification-handler"
    description: "Handles notification messages"
    from:
      uri: "direct:distribution-notification-handler"
      steps:
        - log:
            message: "[NOTIFICATION-HANDLER] Processing notification message"
            loggingLevel: INFO
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_NOTIFICATION_PROCESSING"
            
        # Log notification processing
        - to:
            uri: "kamelet:k-log-tx"
            parameters:
              logLevel: "INFO"
              logSource: "distribution-service"
              logCategory: "BUSINESS"
              correlationId: "${exchangeId}"
              
        # Add notification-specific processing logic here
        - log:
            message: "[NOTIFICATION-HANDLER] Notification message processed and sent"
            
        - to:
            uri: "{{distribution.direct.output-endpoint}}"

- route:
    id: "distribution-default-handler"
    description: "Default handler for unknown message types"
    from:
      uri: "direct:distribution-default-handler"
      steps:
        - log:
            message: "[DEFAULT-HANDLER] Processing unknown message type"
            loggingLevel: WARN
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_DEFAULT_PROCESSING"
            
        # Log default processing
        - to:
            uri: "kamelet:k-log-tx"
            parameters:
              logLevel: "WARN"
              logSource: "distribution-service"
              logCategory: "ROUTE"
              correlationId: "${exchangeId}"
              
        - log:
            message: "[DEFAULT-HANDLER] Message processed with default handler"
            
        - to:
            uri: "{{distribution.direct.output-endpoint}}"

- route:
    id: "distribution-error-handler"
    description: "Handles processing errors"
    from:
      uri: "direct:distribution-error-handler"
      steps:
        - log:
            message: "[ERROR-HANDLER] Handling processing error: ${header.processingError}"
            loggingLevel: ERROR
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_ERROR_HANDLING"
            
        # Log error details
        - to:
            uri: "kamelet:k-log-tx"
            parameters:
              logLevel: "ERROR"
              logSource: "distribution-service"
              logCategory: "ERROR"
              correlationId: "${exchangeId}"
              
        # Add error handling logic here (e.g., send to DLQ, retry, etc.)
        - log:
            message: "[ERROR-HANDLER] Error handled, message processed"

- route:
    id: "distribution-output"
    description: "Final output endpoint for processed messages"
    from:
      uri: "{{distribution.direct.output-endpoint}}"
      steps:
        - log:
            message: "[DISTRIBUTION-OUTPUT] Message processing completed: ${body}"
            loggingLevel: INFO
            
        - setHeader:
            name: "processingStage"
            constant: "DISTRIBUTION_COMPLETED"
            
        # Final logging
        - to:
            uri: "kamelet:k-log-tx"
            parameters:
              logLevel: "INFO"
              logSource: "distribution-service"
              logCategory: "AUDIT"
              correlationId: "${exchangeId}"