apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-kafka-message-publisher
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "K-Kafka Message Publisher"
    description: "Publishes messages to Kafka topics with configurable serializers and delivery options"
    required: [topic, brokers]
    properties:
      topic:
        title: "Kafka Topic"
        type: string
        description: "Name of the Kafka topic to publish messages to"
      brokers:
        title: "Kafka Brokers"
        type: string
        description: "Comma-separated list of Kafka broker addresses"
        default: "localhost:9092"
      key:
        title: "Message Key"
        type: string
        description: "Key for the Kafka message (can use simple expressions like ${header.CorrelationId})"
      keySerializer:
        title: "Key Serializer"
        type: string
        description: "Serializer class for message keys"
        default: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer:
        title: "Value Serializer"
        type: string
        description: "Serializer class for message values"
        default: "org.apache.kafka.common.serialization.StringSerializer"
      requestTimeoutMs:
        title: "Request Timeout"
        type: integer
        description: "Maximum time in milliseconds to wait for the request to complete"
        default: 5000
      connectionMaxIdleMs:
        title: "Connection Max Idle"
        type: integer
        description: "Maximum time in milliseconds a connection can remain idle"
        default: 5000
      retries:
        title: "Retries"
        type: integer
        description: "Number of retries for failed sends"
        default: 3
      requestRequiredAcks:
        title: "Acknowledgments"
        type: string
        description: "Number of acknowledgments the producer requires"
        enum: ["0", "1", "all"]
        default: "1"
      enableIdempotence:
        title: "Enable Idempotence"
        type: boolean
        description: "Enable idempotent producer to avoid duplicate messages"
        default: false
      logMessage:
        title: "Log Message"
        type: string
        description: "Optional log message to publish instead of the body. When provided, this message will be sent to Kafka instead of the exchange body, preserving the original message flow."
      sendHeaders:
        title: "Send Headers"
        type: boolean
        description: "Whether to send Camel exchange headers to Kafka. Set to false to send only the body."
        default: true
  template:
    from:
      uri: "kamelet:source"
      steps:
      # Remove all headers except essential Kafka ones
        - removeHeaders:
              pattern: "*"
              excludePattern: "kafka.*|CamelMessageTimestamp"
        - setHeader:
            name: "PublishTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSZ}"
        - setHeader:
            name: "kafka.KEY"
            simple: "{{key}}"
        # Use logMessage if provided, otherwise use body
        - choice:
            when:
              - simple: "'{{logMessage:}}' != ''"
                steps:
                  # Store original body in exchange property (not header to avoid sending to Kafka)
                  - setProperty:
                      name: "OriginalBodyBackup"
                      simple: "${body}"
                  - setBody:
                      simple: "{{logMessage}}"
                  - log:
                      message: "[K-KAFKA-MESSAGE-PUBLISHER] Publishing log message to topic: {{topic}}, Key: ${header.kafka.KEY}"
                  - to:
                      uri: "kafka:{{topic}}?brokers={{brokers}}&keySerializer={{keySerializer}}&valueSerializer={{valueSerializer}}&requestTimeoutMs={{requestTimeoutMs}}&connectionMaxIdleMs={{connectionMaxIdleMs}}&retries={{retries}}&requestRequiredAcks={{requestRequiredAcks}}&enableIdempotence={{enableIdempotence}}"
                  # Restore original body from exchange property
                  - setBody:
                      simple: "${exchangeProperty.OriginalBodyBackup}"
                  - log:
                      message: "[K-KAFKA-MESSAGE-PUBLISHER] ✅ Log message published to topic: {{topic}}, original body restored"
            otherwise:
              steps:
                - log:
                    message: "[K-KAFKA-MESSAGE-PUBLISHER] Publishing message to topic: {{topic}}, Key: ${header.kafka.KEY}, MessageSize: ${body.length()}"
                - to:
                    uri: "kafka:{{topic}}?brokers={{brokers}}&keySerializer={{keySerializer}}&valueSerializer={{valueSerializer}}&requestTimeoutMs={{requestTimeoutMs}}&connectionMaxIdleMs={{connectionMaxIdleMs}}&retries={{retries}}&requestRequiredAcks={{requestRequiredAcks}}&enableIdempotence={{enableIdempotence}}"
                - log:
                    message: "[K-KAFKA-MESSAGE-PUBLISHER] ✅ Message successfully published to topic: {{topic}}, Key: ${header.kafka.KEY}"