apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-http-message-receiver
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "K-HTTP Message Receiver"
    description: "Consumes JSON messages from REST API, logs receipt details, and routes messages for further processing"
    required: [path]
    properties:
      path:
        title: "REST API path"
        type: string
        default: "/api/messages"
      port:
        title: "HTTP port"
        type: integer
        default: 8080
      consumes:
        title: "Content type consumed"
        type: string
        default: "application/json"
      produces:
        title: "Content type produced"
        type: string
        default: "application/json"
  template:
    from:
      uri: "platform-http:{{path}}"
      parameters:
        httpMethodRestrict: "POST"
      steps:
        - log: 
            message: "[HTTP-RECEIVER] Message received via REST API on {{path}}: ${body}"
            loggingLevel: "INFO"
        
        - set-header:
            name: "Content-Type"
            constant: "{{produces}}"
        
        - set-header:
            name: "messageSource"
            constant: "HTTP_API"
        
        - set-header:
            name: "receiptTimestamp"
            simple: "${date:now:yyyy-MM-dd HH:mm:ss.SSS}"
        
        - set-header:
            name: "receiptChannel"
            constant: "REST_API"
        
        - set-header:
            name: "apiPath"
            simple: "{{path}}"
        
        - set-header:
            name: "httpMethod"
            simple: "${header.CamelHttpMethod}"
        
        - log: 
            message: "[HTTP-RECEIVER] Message metadata set - Source: ${header.messageSource}, Timestamp: ${header.receiptTimestamp}, Path: ${header.apiPath}, Method: ${header.httpMethod}"
            loggingLevel: "DEBUG"
        
        - set-body:
            constant: '{"status": "received", "message": "Message received and routed for processing", "timestamp": "${header.receiptTimestamp}"}'