apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-log-events
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "K-Log Events"
    description: |-
      Creates and publishes detailed log event messages to Kafka for processing monitoring.
    type: object
    properties:
      logMessageTxt:
        title: Log Message Text
        description: The log message text content
        type: string
        default: "Processing message"
      level:
        title: Log Level
        description: Log level (INFO, WARN, DEBUG, ERROR)
        type: string
        enum: ["INFO", "WARN", "DEBUG", "ERROR"]
        default: "INFO"
      kafkaTopicName:
        title: Kafka Topic Name
        description: Kafka topic for log events
        type: string
      brokers:
        title: Kafka Brokers
        description: Kafka broker endpoints
        type: string
      flowCode:
        title: Flow Code
        description: The flow code for logging context
        type: string
      flowId:
        title: Flow ID
        description: The flow ID for logging context
        type: string
      processingTimestamp:
        title: Processing Timestamp
        description: The processing timestamp for the log event
        type: string
  template:
    route:
      id: "k_log_event_{{flowId}}"
      from:
        uri: "kamelet:source"
        steps:
        
        # Log route ID at the start
        - log:
            message: "K-LOG-EVENTS: Starting processing with route ID: ${routeId}"
            loggingLevel: INFO
        # Error handling with doTry/doCatch
        - doTry:
            steps:
              # Store original body before processing
              - setHeader:
                  name: "OriginalBody"
                  simple: "${body}"
              # Transform processingTimestamp from compact format to ISO format
              - setHeader:
                  name: "FormattedProcessingTimestamp" 
                  simple: "${bean:com.pixel.v2.util.TimestampConverter?method=convertToISO('{{processingTimestamp}}')}"
            
              - setHeader:
                  name: "logMessage"
                  simple: |
                    {
                      "logId": "LOG-${date:now:yyyyMMddHHmmssSSS}",
                      "datats": "${header.FormattedProcessingTimestamp}",
                      "flowId": "{{flowId}}",
                      "halfFlowId": "{{flowId}}-HALF",
                      "flowCode": "{{flowCode}}",
                      "halfFlowCode": "{{flowCode}}-HALF",
                      "contextId": "${header.CorrelationId}",
                      "clientLogTimestamp": "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}",
                      "dbLogTimestamp": "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}",
                      "txt": "{{logMessageTxt}}",
                      "longTxt": "[{{level}}] {{logMessageTxt}}",
                      "logRole": "{{level}}",
                      "code": "{{level}}",
                      "customStep": "{{logMessageTxt}}",
                      "component": "processing-flow",
                      "instanceId": "I${date:now:yyMMddHHmmss}",
                      "servicePath": "${header.queueName}",
                      "processPath": "/processing",
                      "refFlowId": 0,
                      "beginProcess": "${header.FormattedProcessingTimestamp}",
                      "endProcess": null,
                      "contextTimestamp": "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}",
                      "msgSentTimestamp": "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}",
                      "messagingType": "JMS",
                      "msgId": "${header.MessageId}",
                      "msgPriority": 1,
                      "msgCorrelationId": "${header.CorrelationId}",
                      "msgSourceSystem": "PIXEL-V2",
                      "msgPrivateContext": "${header.toString()}",
                      "msgTransactionId": "${header.MessageId}",
                      "msgProperties": "{}",
                      "msgBatchName": null,
                      "msgBatchMsgNo": null,
                      "msgBatchSize": null,
                      "xmlMsgAction": null,
                      "msgResubmitInd": "N",
                      "msgBody": "",
                      "logDay": "${date:now:yyyy-MM-dd}"
                    }
              - log:
                  message: "K-LOG-EVENTS (Route: ${routeId}): body=${header.logMessage}"
                  loggingLevel: DEBUG
              - setBody:
                  simple: "${header.logMessage}"

              # - to:
              #     uri: "kafka:{{kafkaTopicName}}?brokers={{brokers}}&key={{flowId}}&keySerializer=org.apache.kafka.common.serialization.StringSerializer&valueSerializer=org.apache.kafka.common.serialization.StringSerializer"

              - toD: "kamelet:k-kafka-publisher?kafkaTopicName=${header.KafkaLogTopicName}&brokers=${header.Brokers}&key={{flowId}}"
            doCatch:
              - exception: "java.lang.Exception"
                steps:
                  - log:
                      message: "K-LOG-EVENTS ERROR: Failed to process log event - ${exception.message}"
                      loggingLevel: ERROR
                  - setBody:
                      simple: "${header.OriginalBody}"
        # Always restore original body at the end
        - setBody:
            simple: "${header.OriginalBody}"