apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-log-events
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "K-Log Events"
    description: |-
      Creates and publishes detailed log event messages to Kafka for processing monitoring.
    type: object
    properties:
      logMessageTxt:
        title: Log Message Text
        description: The log message text content
        type: string
        default: "Processing message"
      level:
        title: Log Level
        description: Log level (INFO, WARN, DEBUG, ERROR)
        type: string
        enum: ["INFO", "WARN", "DEBUG", "ERROR"]
        default: "INFO"
      flowCode:
        title: Flow Code
        description: The flow code for logging context
        type: string
      flowId:
        title: Flow ID
        description: The flow ID for logging context
        type: string
      processingTimestamp:
        title: Processing Timestamp
        description: The processing timestamp for the log event
        type: string
      contextId:
        title: Context ID
        description: The context ID for the log event
        type: string
      component:
        title: Component
        description: The component generating the log event
        type: string
      kafkaTopicName:
        title: Kafka Topic Name
        description: Kafka topic to publish log events to
      brokers:
        title: Kafka Brokers
        description: Kafka broker endpoints
        type: string
      isError:
        title: Is Error
        description: Flag indicating if the log event is an error
        type: boolean
        default: false
  template:
    route:
      id: "k_log_event_{{flowId}}"
      from:
        uri: "kamelet:source"
        steps:
        
        # Log route ID at the start
        - log:
            message: "K-LOG-EVENTS: Starting processing with route ID: ${routeId}"
            loggingLevel: DEBUG
        # Error handling with doTry/doCatch
        - doTry:
            steps:
              # Store original body before processing
              - setHeader:
                  name: "OriginalBody"
                  simple: "${body}"
              # Set hostname header from property (configured via Spring application.properties)
              - setHeader:
                  name: "Hostname"
                  simple: "${properties:pixel.hostname}"
              # Transform processingTimestamp from compact format to ISO format
              - setHeader:
                  name: "FormattedProcessingTimestamp" 
                  simple: "${bean:com.pixel.v2.util.TimestampConverter?method=convertToISO('{{processingTimestamp}}')}"
            
              # Choose log message format based on isError flag
              - choice:
                  when:
                    - simple: "{{isError}} == true"
                      steps:
                        - setHeader:
                            name: "LogMessage"
                            simple: |
                              {
                                "logid": "ERR-${date:now:yyyyMMddHHmmssSSS}",
                                "datats": "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}",
                                "errtimestamp": "${header.FormattedProcessingTimestamp}",
                                "component": "{{component}}",
                                "instanceid": "${header.Hostname}",
                                "processstack": "${header.OriginalRouteId}",
                                "rootprocesspath": "{{flowCode}}",
                                "code": "{{level}}_{{contextId}}",
                                "description": "{{logMessageTxt}}",
                                "shortdesc": "${header.ErrorType}",
                                "type": "E",
                                "severity": 3,
                                "stack": "${header.ErrorDetails}",
                                "input": "${header.OriginalBody}",
                                "debugdata": "{ \"flowId\": \"{{flowId}}\", \"flowCode\": \"{{flowCode}}\", \"contextId\": \"{{contextId}}\" }"
                              }
                  otherwise:
                    steps:
                      - setHeader:
                          name: "LogMessage"
                          simple: |
                            {
                              "logId": "LOG-${date:now:yyyyMMddHHmmssSSS}",
                              "datats": "${header.FormattedProcessingTimestamp}",
                              "flowId": "{{flowId}}",
                              "halfFlowId": "{{flowId}}-HALF",
                              "flowCode": "{{flowCode}}",
                              "halfFlowCode": "{{flowCode}}-HALF",
                              "contextId": "{{contextId}}",
                              "clientLogTimestamp": "${header.FormattedProcessingTimestamp}",
                              "txt": "{{logMessageTxt}}",
                              "longTxt": "${header.Hostname}",
                              "logRole": "{{level}}",
                              "code": "{{level}}",
                              "customStep": "{{logMessageTxt}}",
                              "component": "{{component}}",
                              "instanceId": "I-${date:now:yyMMddHHmmss}",
                              "servicePath": "",
                              "processPath": "processing",
                              "refFlowId": 0,
                              "beginProcess": "${header.FormattedProcessingTimestamp}",
                              "endProcess": null,
                              "contextTimestamp": "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}",
                              "msgSentTimestamp": "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}",
                              "messagingType": "JMS",
                              "msgId": "${header.MessageId}",
                              "msgPriority": 1,
                              "msgCorrelationId": "${header.CorrelationId}",
                              "msgSourceSystem": "PIXEL-V2",
                              "msgPrivateContext": "",
                              "msgTransactionId": "${header.MessageId}",
                              "msgProperties": "{}",
                              "msgBatchName": null,
                              "msgBatchMsgNo": null,
                              "msgBatchSize": null,
                              "xmlMsgAction": null,
                              "msgResubmitInd": "N",
                              "msgBody": "",
                              "logDay": "${date:now:yyyy-MM-dd}"
                            }

              - setBody:
                  simple: "${header.LogMessage}"
              - log:
                  message: "[{{component}}] ${header.Hostname} - {{logMessageTxt}} - brokers: {{brokers}}, topic: {{kafkaTopicName}}"
                  loggingLevel: INFO


              - toD: "kamelet:k-kafka-log-publisher?kafkaTopicName={{kafkaTopicName}}&brokers={{brokers}}&key={{flowId}}"
            doCatch:
              - exception: "java.lang.Exception"
                steps:
                  - log:
                      message: "K-LOG-EVENTS ERROR: Failed to process log event - ${exception.message}"
                      loggingLevel: ERROR
                  - setBody:
                      simple: "${header.OriginalBody}"
        # Always restore original body at the end
        - setBody:
            simple: "${header.OriginalBody}"