apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: k-xsl-transformation
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "K-XSL Transformation"
    description: "Transforms XML messages (single or collection) using XSL stylesheets stored in the kamelet's resource folder. Supports both single String messages and Collection<String> for batch transformation."
    required: [xslFileName]
    properties:
      xslFileName:
        title: "XSL File Name"
        type: string
        description: "Name of the XSL stylesheet file to use for transformation (file must exist in /xsl folder)"
        example: "pacs-008-to-simplified.xsl"
      transformationMode:
        title: "Transformation Mode"
        type: string
        description: "Transformation mode: STRICT (stop on error) or LENIENT (log warnings but continue)"
        default: "STRICT"
        enum: ["STRICT", "LENIENT"]
      enableDetailedErrors:
        title: "Enable Detailed Error Messages"
        type: boolean
        description: "Include detailed XSL transformation error messages in exceptions"
        default: true
      namespaceAware:
        title: "Namespace Aware Transformation"
        type: boolean
        description: "Enable namespace-aware XML parsing and transformation"
        default: true
  template:
    from:
      uri: "kamelet:source"
      steps:
        # Set transformation headers
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}"
        - setHeader:
            name: "ContextId"
            simple: "xsl-transformation-${uuid}"
            
        - setHeader:
            name: "XslFileName"
            simple: "{{xslFileName}}"
            
        - setHeader:
            name: "TransformationMode"
            simple: "{{transformationMode}}"
        
        - toD:
            uri: "kamelet:k-log-events?kafkaTopicName=${headers.KafkaLogTopicName}&brokers=${headers.Brokers}&flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&logMessageTxt=Start transformation - flowOccurId: ${header.FlowOccurId}, XSL: {{xslFileName}}&level=INFO&processingTimestamp=${header.ProcessingTimestamp}&contextId=${header.ContextId}&component=K-XSL-TRANSFORMATION"
            pattern: "InOnly"
            
        # Transform XML using XSL stylesheet via custom processor
        # Supports both single String messages and Collection<String> for batch transformation
        - to:
            uri: "bean:xslTransformationProcessor"
          
        - setHeader:
            name: "ProcessingTimestamp"
            simple: "${date:now:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}"
        
        - toD:
            uri: "kamelet:k-log-events?kafkaTopicName=${headers.KafkaLogTopicName}&brokers=${headers.Brokers}&flowId=${header.FlowOccurId}&flowCode=${header.FlowCode}&logMessageTxt=End transformation - flowOccurId: ${header.FlowOccurId}, XSL: {{xslFileName}}&level=INFO&processingTimestamp=${header.ProcessingTimestamp}&contextId=${header.ContextId}&component=K-XSL-TRANSFORMATION"
            pattern: "InOnly"
            
        
            
        # Continue to next step (transformation passed)
        - to: "kamelet:sink"